import { createClient } from "@supabase/supabase-js";

type Incoming={channel?:"whatsapp"|"test"|"admin";external_user_id?:string;external_message_id?:string;message?:string};
type Session={id:string;channel:string;external_user_id:string;flow:string;state:string;context:Record<string,unknown>;status:string};
type Button={id:string;title:string};
type Ui={type:"buttons";body:string;buttons:Button[]}|{type:"list";body:string;button:string;rows:{id:string;title:string;description?:string}[]};
type Outbound={to:string;reply:string;ui?:Ui};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
function secretKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const p=JSON.parse(raw);if(typeof p.default==="string"&&p.default)return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const norm=(s:string)=>s.trim().toLowerCase();
function parseLocation(text:string){const p=text.split(",").map(x=>x.trim()).filter(Boolean);return p.length<2?null:{suburb:p[0],city:p[1],province:p[2]??null}}
async function save(s:any,x:Session){const {error}=await s.from("conversation_sessions").update({flow:x.flow,state:x.state,context:x.context,status:x.status}).eq("id",x.id);if(error)throw error}
async function log(s:any,id:string,direction:"inbound"|"outbound",body:string,external?:string,payload:Record<string,unknown>={}){const {error}=await s.from("conversation_messages").insert({session_id:id,direction,external_message_id:external??null,body,payload});return error}
async function reply(s:any,x:Session,message:string,ui?:Ui,extra:Record<string,unknown>={}){await log(s,x.id,"outbound",message,undefined,ui?{ui}:{});return json({ok:true,session_id:x.id,flow:x.flow,state:x.state,reply:message,ui,...extra})}
async function skills(s:any){const {data,error}=await s.from("skills").select("code,name").eq("active",true).order("name");if(error)throw error;return data??[]}
const roleUi:Ui={type:"buttons",body:"Welcome to HandyConnect. What would you like to do?",buttons:[{id:"ROLE_CUSTOMER",title:"Find a handyman"},{id:"ROLE_HANDYMAN",title:"Find work"}]};
const handymanUi=(available=false):Ui=>({type:"buttons",body:available?"You're available for jobs. What would you like to do?":"Handyman menu",buttons:[{id:available?"GO_OFFLINE":"GO_AVAILABLE",title:available?"Go offline":"I'm available"},{id:"MY_JOBS",title:"My jobs"},{id:"MY_PROFILE",title:"My profile"}]});
const customerUi:Ui={type:"buttons",body:"What would you like to do?",buttons:[{id:"REQUEST_HELP",title:"Request help"},{id:"CUSTOMER_JOBS",title:"My jobs"}]};
async function identity(s:any,phone:string){const h=await s.from("handymen").select("id,full_name,business_name,availability_status,available_until").eq("phone",phone).maybeSingle();if(h.error)throw h.error;const c=await s.from("customers").select("id,full_name").eq("phone",phone).maybeSingle();if(c.error)throw c.error;return{handyman:h.data,customer:c.data}}
async function resetToMenu(s:any,x:Session,phone:string){const who=await identity(s,phone);x.flow="ready";x.state="ready";x.context={};x.status="active";await save(s,x);if(who.handyman)return reply(s,x,`Welcome back${who.handyman.full_name?`, ${who.handyman.full_name}`:""}.`,handymanUi(who.handyman.availability_status==="available"));if(who.customer)return reply(s,x,"Welcome back to HandyConnect.",customerUi);x.flow="entry";x.state="choose_role";await save(s,x);return reply(s,x,roleUi.body,roleUi)}
async function handymanJobs(s:any,handymanId:string){const {data:matches,error}=await s.from("job_matches").select("id,job_id,status,offered_at").eq("handyman_id",handymanId).in("status",["offered","accepted"]).order("offered_at",{ascending:false}).limit(10);if(error)throw error;if(!matches?.length)return[];const ids=[...new Set(matches.map((m:any)=>m.job_id))];const {data:jobs,error:je}=await s.from("jobs").select("id,description,suburb,city,status").in("id",ids);if(je)throw je;return matches.map((m:any)=>({...m,job:jobs?.find((j:any)=>j.id===m.job_id)}))}

Deno.serve(async(req)=>{
 if(req.method==="GET")return json({service:"conversation-engine",status:"ok"});
 if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 const key=secretKey();if(!key||req.headers.get("apikey")!==key)return json({error:"unauthorized"},401);
 const s=createClient(Deno.env.get("SUPABASE_URL")??"",key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
 let input:Incoming;try{input=await req.json()}catch{return json({error:"invalid_json"},400)}
 const channel=input.channel??"test",user=input.external_user_id?.trim(),text=input.message?.trim();if(!user||!text)return json({error:"external_user_id_and_message_are_required"},400);
 try{
  let {data:session,error}=await s.from("conversation_sessions").select("id,channel,external_user_id,flow,state,context,status").eq("channel",channel).eq("external_user_id",user).maybeSingle();if(error)throw error;
  if(!session){const c=await s.from("conversation_sessions").insert({channel,external_user_id:user}).select("id,channel,external_user_id,flow,state,context,status").single();if(c.error)throw c.error;session=c.data}
  const x=session as Session;const inbound=await log(s,x.id,"inbound",text,input.external_message_id);if(inbound){if(inbound.code==="23505"&&input.external_message_id)return json({ok:true,duplicate:true,session_id:x.id});throw inbound}
  const action=text.trim();
  if(["hi","hello","menu","start","reset"].includes(norm(action)))return resetToMenu(s,x,user);

  if(action==="ROLE_HANDYMAN"){x.flow="handyman_onboarding";x.state="capture_name";x.context={};x.status="active";await save(s,x);return reply(s,x,"Great. What's your full name?")}
  if(action==="ROLE_CUSTOMER"||action==="REQUEST_HELP"){x.flow="customer_job";x.state="capture_job_description";x.context={};x.status="active";await save(s,x);return reply(s,x,"Tell me briefly what needs fixing. Example: My door handle is broken.")}

  const who=await identity(s,user);
  if(action==="GO_AVAILABLE"&&who.handyman){const r=await s.rpc("set_handyman_availability",{p_phone:user,p_status:"available",p_hours:8});if(r.error)throw r.error;return reply(s,x,"You're now available for matching for the next 8 hours.",handymanUi(true))}
  if(action==="GO_OFFLINE"&&who.handyman){const r=await s.rpc("set_handyman_availability",{p_phone:user,p_status:"offline",p_hours:8});if(r.error)throw r.error;return reply(s,x,"You're offline. You won't receive new job offers until you mark yourself available.",handymanUi(false))}
  if(action==="MY_PROFILE"&&who.handyman){const areas=await s.from("service_areas").select("suburb,city,province").eq("handyman_id",who.handyman.id);const hs=await s.from("handyman_skills").select("skill_id").eq("handyman_id",who.handyman.id);const skillIds=(hs.data??[]).map((z:any)=>z.skill_id);const sk=skillIds.length?await s.from("skills").select("id,name").in("id",skillIds):{data:[]};const body=`${who.handyman.full_name}\nAvailability: ${who.handyman.availability_status}\nSkills: ${(sk.data??[]).map((z:any)=>z.name).join(", ")||"None"}\nArea: ${(areas.data??[]).map((z:any)=>[z.suburb,z.city].filter(Boolean).join(", ")).join("; ")||"Not set"}`;return reply(s,x,body,handymanUi(who.handyman.availability_status==="available"))}
  if(action==="MY_JOBS"&&who.handyman){const rows=await handymanJobs(s,who.handyman.id);if(!rows.length)return reply(s,x,"You don't have any active job offers or assigned jobs yet.",handymanUi(who.handyman.availability_status==="available"));const offered=rows.filter((r:any)=>r.status==="offered");if(offered.length){const r:any=offered[0];return reply(s,x,`Job offer: ${r.job?.description??"Job"}\nLocation: ${[r.job?.suburb,r.job?.city].filter(Boolean).join(", ")}`,{type:"buttons",body:"Would you like this job?",buttons:[{id:`ACCEPT:${r.id}`,title:"Accept"},{id:`DECLINE:${r.id}`,title:"Decline"},{id:"MY_JOBS",title:"More jobs"}]},{jobs:rows})}return reply(s,x,rows.map((r:any)=>`• ${r.job?.description??"Job"} — ${r.job?.status??r.status}`).join("\n"),handymanUi(who.handyman.availability_status==="available"),{jobs:rows})}
  if(action.startsWith("ACCEPT:")&&who.handyman){const matchId=action.slice(7);const own=await s.from("job_matches").select("id").eq("id",matchId).eq("handyman_id",who.handyman.id).maybeSingle();if(own.error)throw own.error;if(!own.data)return reply(s,x,"That job offer isn't available to this account.",handymanUi(who.handyman.availability_status==="available"));const a=await s.rpc("accept_job_match",{p_match_id:matchId});if(a.error)return reply(s,x,"That job has already been taken or is no longer available.",handymanUi(who.handyman.availability_status==="available"));return reply(s,x,"Job accepted. It's now in My jobs.",handymanUi(who.handyman.availability_status==="available"),{assignment_id:a.data})}
  if(action.startsWith("DECLINE:")&&who.handyman){const matchId=action.slice(8);const d=await s.from("job_matches").update({status:"declined",responded_at:new Date().toISOString()}).eq("id",matchId).eq("handyman_id",who.handyman.id).eq("status","offered");if(d.error)throw d.error;return reply(s,x,"Job declined. We'll keep looking for relevant opportunities.",handymanUi(who.handyman.availability_status==="available"))}
  if(action==="CUSTOMER_JOBS"&&who.customer){const j=await s.from("jobs").select("id,description,suburb,city,status,created_at").eq("customer_id",who.customer.id).order("created_at",{ascending:false}).limit(5);if(j.error)throw j.error;return reply(s,x,j.data?.length?j.data.map((z:any)=>`• ${z.description} — ${z.status}`).join("\n"):"You haven't requested any jobs yet.",customerUi,{jobs:j.data??[]})}

  if(x.flow==="handyman_onboarding"){
   if(x.state==="capture_name"){if(text.length<2)return reply(s,x,"Please send your full name.");x.context={...x.context,full_name:text};x.state="capture_business";await save(s,x);return reply(s,x,"What's your business name? Reply SKIP if you don't use one.")}
   if(x.state==="capture_business"){x.context={...x.context,business_name:norm(text)==="skip"?null:text};x.state="capture_skills";await save(s,x);const sk=await skills(s);return reply(s,x,"Choose your main skill.",{type:"list",body:"Select the skill that best describes the work you do.",button:"Choose skill",rows:sk.map((z:any)=>({id:`HSKILL:${z.code}`,title:z.name}))})}
   if(x.state==="capture_skills"){const code=action.startsWith("HSKILL:")?action.slice(7):norm(text).replace(/\s+/g,"_");const sk=await s.from("skills").select("code,name").eq("code",code).maybeSingle();if(sk.error)throw sk.error;if(!sk.data){const all=await skills(s);return reply(s,x,"Please choose a skill from the menu.",{type:"list",body:"Select a skill",button:"Choose skill",rows:all.map((z:any)=>({id:`HSKILL:${z.code}`,title:z.name}))})}x.context={...x.context,skill_codes:[sk.data.code]};x.state="capture_location";await save(s,x);return reply(s,x,"Where do you mainly work? Send: Suburb, City, Province. Example: Bellville, Cape Town, Western Cape")}
   if(x.state==="capture_location"){const loc=parseLocation(text);if(!loc)return reply(s,x,"Please send at least Suburb, City. Example: Bellville, Cape Town");const c=x.context as any;const r=await s.rpc("onboard_handyman",{p_phone:user,p_full_name:c.full_name,p_business_name:c.business_name??null,p_email:null,p_skill_codes:c.skill_codes??[],p_city:loc.city,p_suburb:loc.suburb,p_province:loc.province});if(r.error)throw r.error;x.flow="ready";x.state="ready";x.context={};x.status="active";await save(s,x);return reply(s,x,"Registration complete. You're offline until you choose 'I'm available'. Your Free plan includes 3 job opportunities per month.",handymanUi(false),{handyman_id:r.data})}
  }

  if(x.flow==="customer_job"){
   if(x.state==="capture_job_description"){if(text.length<4)return reply(s,x,"Please describe the job in a few words.");x.context={job_description:text};x.state="capture_job_skill";await save(s,x);const sk=await skills(s);return reply(s,x,"What kind of work is this?",{type:"list",body:"Choose the closest category.",button:"Choose category",rows:sk.map((z:any)=>({id:`JSKILL:${z.code}`,title:z.name}))})}
   if(x.state==="capture_job_skill"){const code=action.startsWith("JSKILL:")?action.slice(7):norm(text).replace(/\s+/g,"_");const sk=await s.from("skills").select("id,code,name").eq("code",code).maybeSingle();if(sk.error)throw sk.error;if(!sk.data){const all=await skills(s);return reply(s,x,"Please choose a category from the menu.",{type:"list",body:"Choose the closest category.",button:"Choose category",rows:all.map((z:any)=>({id:`JSKILL:${z.code}`,title:z.name}))})}x.context={...x.context,skill_id:sk.data.id,skill_name:sk.data.name};x.state="capture_job_location";await save(s,x);return reply(s,x,"Where is the job? Send: Suburb, City, Province. Example: Pinelands, Cape Town, Western Cape")}
   if(x.state==="capture_job_location"){const loc=parseLocation(text);if(!loc)return reply(s,x,"Please send at least Suburb, City. Example: Pinelands, Cape Town");const c=x.context as any;const cust=await s.from("customers").upsert({phone:user},{onConflict:"phone"}).select("id").single();if(cust.error)throw cust.error;const job=await s.from("jobs").insert({customer_id:cust.data.id,skill_id:c.skill_id,description:c.job_description,suburb:loc.suburb,city:loc.city,province:loc.province,status:"matching"}).select("id").single();if(job.error)throw job.error;const cand=await s.rpc("find_job_candidates",{p_job_id:job.data.id,p_limit:5});if(cand.error)throw cand.error;const rows=cand.data??[];let outbound:Outbound[]=[];if(rows.length){const matchRows=rows.map((z:any)=>({job_id:job.data.id,handyman_id:z.handyman_id,match_score:z.score,status:"offered"}));const ins=await s.from("job_matches").insert(matchRows).select("id,handyman_id");if(ins.error)throw ins.error;const hids=ins.data.map((z:any)=>z.handyman_id);const hp=await s.from("handymen").select("id,phone").in("id",hids);if(hp.error)throw hp.error;outbound=ins.data.map((m:any)=>{const phone=hp.data?.find((h:any)=>h.id===m.handyman_id)?.phone;return phone?{to:phone,reply:`New ${c.skill_name??"HandyConnect"} job: ${c.job_description}\nLocation: ${loc.suburb}, ${loc.city}`,ui:{type:"buttons",body:"Are you interested?",buttons:[{id:`ACCEPT:${m.id}`,title:"Accept"},{id:`DECLINE:${m.id}`,title:"Decline"}]}}:null}).filter(Boolean) as Outbound[]}
    x.flow="ready";x.state="ready";x.context={};x.status="active";await save(s,x);return reply(s,x,rows.length?`Request sent to ${rows.length} available handyman${rows.length===1?"":"s"}. We'll confirm as soon as one accepts.`:"Your job is saved, but there are no matching handymen marked available right now.",customerUi,{job_id:job.data.id,candidate_count:rows.length,outbound})}
  }
  return resetToMenu(s,x,user);
 }catch(e){console.error(e);return json({error:"internal_error"},500)}
});
