import { createClient } from "@supabase/supabase-js";

type Incoming={channel?:"whatsapp"|"test"|"admin";external_user_id?:string;external_message_id?:string;message?:string};
type Session={id:string;channel:string;external_user_id:string;flow:string;state:string;context:Record<string,unknown>;status:string};
type Button={id:string;title:string};
type Ui={type:"buttons";body:string;buttons:Button[]}|{type:"list";body:string;button:string;rows:{id:string;title:string;description?:string}[]};
type Outbound={to:string;reply:string;ui?:Ui};

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
function secretKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const p=JSON.parse(raw);if(typeof p.default==="string"&&p.default)return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const norm=(s:string)=>s.trim().toLowerCase();
function parseLocation(text:string){const p=text.split(",").map(x=>x.trim()).filter(Boolean);return p.length<2?null:{suburb:p[0],city:p[1],province:p[2]??null}}
async function save(s:any,x:Session){const {error}=await s.from("conversation_sessions").update({flow:x.flow,state:x.state,context:x.context,status:x.status}).eq("id",x.id);if(error)throw error}
async function log(s:any,id:string,direction:"inbound"|"outbound",body:string,external?:string,payload:Record<string,unknown>={}){const {error}=await s.from("conversation_messages").insert({session_id:id,direction,external_message_id:external??null,body,payload});return error}
async function reply(s:any,x:Session,message:string,ui?:Ui,extra:Record<string,unknown>={}){await log(s,x.id,"outbound",message,undefined,ui?{ui}:{});return json({ok:true,session_id:x.id,flow:x.flow,state:x.state,reply:message,ui,...extra})}
async function skills(s:any){const {data,error}=await s.from("skills").select("id,code,name").eq("active",true).order("name");if(error)throw error;return data??[]}

const roleUi:Ui={type:"buttons",body:"Welcome to HandyConnect. What would you like to do?",buttons:[{id:"ROLE_CUSTOMER",title:"Find a handyman"},{id:"ROLE_HANDYMAN",title:"Find work"}]};
const customerUi:Ui={type:"buttons",body:"What would you like to do?",buttons:[{id:"REQUEST_HELP",title:"Request help"},{id:"CUSTOMER_JOBS",title:"My jobs"}]};
const handymanUi=(available=false):Ui=>({type:"buttons",body:available?"You're available for jobs.":"Handyman menu",buttons:[{id:available?"GO_OFFLINE":"GO_AVAILABLE",title:available?"Go offline":"I'm available"},{id:"MY_JOBS",title:"My jobs"},{id:"MY_PROFILE",title:"My profile"}]});

const categoryPages=[
 ["appliance_repair","plumbing","electrical","general_handyman","carpentry","painting","locksmith","tiling","aircon_hvac"],
 ["solar_inverter","cctv_security","gates_garage_doors","roofing","waterproofing","ceilings_drywall","flooring","glazing_windows","welding_metalwork"],
 ["gardening_landscaping","pool_maintenance","paving","gutters","pest_control","furniture_assembly","moving_small_jobs"]
];
async function categoryUi(s:any,prefix:"J"|"H",page=0):Promise<Ui>{const all=await skills(s);const map=new Map(all.map((z:any)=>[z.code,z]));const rows=(categoryPages[page]??categoryPages[0]).map(code=>map.get(code)).filter(Boolean).map((z:any)=>({id:`${prefix}SKILL:${z.code}`,title:z.name}));if(page<categoryPages.length-1)rows.push({id:`${prefix}CATPAGE:${page+1}`,title:"More services"});if(page>0)rows.push({id:`${prefix}CATPAGE:${page-1}`,title:"Previous services"});return{type:"list",body:"Choose the closest service category.",button:"Choose service",rows:rows.slice(0,10)}}
function inferSkill(text:string){const t=norm(text);const rules:[string,string[]][]=[
 ["appliance_repair",["fridge","freezer","washing machine","washer","dishwasher","stove","oven","microwave","tumble dryer","dryer","appliance"]],
 ["plumbing",["pipe","tap","toilet","geyser","leak","drain","plumb","basin","sink"]],
 ["electrical",["plug","socket","light","electric","breaker","db board","power","wiring"]],
 ["locksmith",["lock","key","locked out"]],
 ["aircon_hvac",["aircon","air conditioner","hvac"]],
 ["solar_inverter",["solar","inverter","battery backup"]],
 ["cctv_security",["cctv","camera","alarm","security system"]],
 ["gates_garage_doors",["garage door","gate motor","electric gate"]],
 ["roofing",["roof","roof tile"]],
 ["waterproofing",["waterproof","damp","water ingress"]],
 ["tiling",["tile","tiling"]],
 ["painting",["paint","painting"]],
 ["carpentry",["cupboard","cabinet","wood","carpentry","wooden door"]],
 ["glazing_windows",["window","glass","glazing"]],
 ["welding_metalwork",["weld","metal","steel"]],
 ["gardening_landscaping",["garden","grass","lawn","tree","landscap"]],
 ["pool_maintenance",["pool","swimming pool"]],
 ["pest_control",["cockroach","termite","rat","mice","pest"]],
 ["furniture_assembly",["assemble","flatpack","furniture assembly"]],
 ["ceilings_drywall",["ceiling","drywall","partition"]],
 ["flooring",["laminate","vinyl floor","flooring"]],
 ["gutters",["gutter","downpipe"]],
 ["paving",["paving","paver"]]
 ];for(const [code,words] of rules)if(words.some(w=>t.includes(w)))return code;return null}

async function identity(s:any,phone:string){const h=await s.from("handymen").select("id,full_name,business_name,phone,availability_status,available_until,average_rating").eq("phone",phone).maybeSingle();if(h.error)throw h.error;const c=await s.from("customers").select("id,full_name,phone").eq("phone",phone).maybeSingle();if(c.error)throw c.error;return{handyman:h.data,customer:c.data}}
async function resetToMenu(s:any,x:Session,phone:string){const who=await identity(s,phone);x.flow="ready";x.state="ready";x.context={};x.status="active";await save(s,x);if(who.handyman)return reply(s,x,`Welcome back${who.handyman.full_name?`, ${who.handyman.full_name}`:""}.`,handymanUi(who.handyman.availability_status==="available"));if(who.customer)return reply(s,x,"Welcome back to HandyConnect.",customerUi);x.flow="entry";x.state="choose_role";await save(s,x);return reply(s,x,roleUi.body,roleUi)}
async function getJobAndCustomer(s:any,jobId:string){const j=await s.from("jobs").select("id,customer_id,description,suburb,city,status").eq("id",jobId).single();if(j.error)throw j.error;const c=await s.from("customers").select("id,phone,full_name").eq("id",j.data.customer_id).single();if(c.error)throw c.error;return{job:j.data,customer:c.data}}

Deno.serve(async(req)=>{
 if(req.method==="GET")return json({service:"conversation-engine",status:"ok"});
 if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 const key=secretKey();if(!key||req.headers.get("apikey")!==key)return json({error:"unauthorized"},401);
 const s=createClient(Deno.env.get("SUPABASE_URL")??"",key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
 let input:Incoming;try{input=await req.json()}catch{return json({error:"invalid_json"},400)}
 const channel=input.channel??"test",user=input.external_user_id?.trim(),text=input.message?.trim();if(!user||!text)return json({error:"external_user_id_and_message_are_required"},400);
 try{
  let {data:session,error}=await s.from("conversation_sessions").select("id,channel,external_user_id,flow,state,context,status").eq("channel",channel).eq("external_user_id",user).maybeSingle();if(error)throw error;
  if(!session){const c=await s.from("conversation_sessions").insert({channel,external_user_id:user}).select("id,channel,external_user_id,flow,state,context,status").single();if(c.error)throw c.error;session=c.data}
  const x=session as Session;const inbound=await log(s,x.id,"inbound",text,input.external_message_id);if(inbound){if(inbound.code==="23505"&&input.external_message_id)return json({ok:true,duplicate:true,session_id:x.id});throw inbound}
  const action=text.trim();
  if(["hi","hello","menu","start","reset"].includes(norm(action)))return resetToMenu(s,x,user);
  const who=await identity(s,user);

  if(action==="ROLE_HANDYMAN"||action==="ROLE_HANDYMAN_TERMS_ACCEPTED"){if(who.handyman)return reply(s,x,"You're already registered as a handyman.",handymanUi(who.handyman.availability_status==="available"));x.flow="handyman_onboarding";x.state="capture_name";x.context={terms_accepted:action==="ROLE_HANDYMAN_TERMS_ACCEPTED"};x.status="active";await save(s,x);return reply(s,x,"Great. What's your full name?")}
  if(action==="ROLE_CUSTOMER"||action==="REQUEST_HELP"){x.flow="customer_job";x.state="capture_job_description";x.context={};x.status="active";await save(s,x);return reply(s,x,"Tell me what needs fixing. You can be natural — for example: ‘My fridge is not cooling.’")}

  if(action.startsWith("JCATPAGE:")){const page=Number(action.split(":")[1])||0;return reply(s,x,"Choose a service.",await categoryUi(s,"J",page))}
  if(action.startsWith("HCATPAGE:")){const page=Number(action.split(":")[1])||0;return reply(s,x,"Choose your main skill.",await categoryUi(s,"H",page))}

  if(action==="GO_AVAILABLE"&&who.handyman){const r=await s.rpc("set_handyman_availability",{p_phone:user,p_status:"available",p_hours:8});if(r.error)throw r.error;const pending=await s.rpc("offer_waiting_jobs_to_handyman",{p_phone:user,p_limit:5});if(pending.error)throw pending.error;const jobs=pending.data??[];if(jobs.length){const j=jobs[0];return reply(s,x,`You're available. I also found ${jobs.length} waiting job${jobs.length===1?"":"s"} that match you.\n\n${j.skill_name}: ${j.description}\n${[j.suburb,j.city].filter(Boolean).join(", ")}`,{type:"buttons",body:"Would you like this job?",buttons:[{id:`ACCEPT:${j.match_id}`,title:"Accept"},{id:`DECLINE:${j.match_id}`,title:"Decline"},{id:"MY_JOBS",title:"My jobs"}]})}return reply(s,x,"You're available for matching for the next 8 hours. If a suitable waiting job appears, it will be offered to you.",handymanUi(true))}
  if(action==="GO_OFFLINE"&&who.handyman){const r=await s.rpc("set_handyman_availability",{p_phone:user,p_status:"offline",p_hours:8});if(r.error)throw r.error;return reply(s,x,"You're offline. You won't receive new job offers until you mark yourself available.",handymanUi(false))}

  if(action==="MY_PROFILE"&&who.handyman){const areas=await s.from("service_areas").select("suburb,city,province").eq("handyman_id",who.handyman.id);const hs=await s.from("handyman_skills").select("skill_id").eq("handyman_id",who.handyman.id);const ids=(hs.data??[]).map((z:any)=>z.skill_id);const sk=ids.length?await s.from("skills").select("id,name").in("id",ids):{data:[]};const body=`${who.handyman.full_name}\nAvailability: ${who.handyman.availability_status}\nRating: ${who.handyman.average_rating??0}/5\nSkills: ${(sk.data??[]).map((z:any)=>z.name).join(", ")||"None"}\nArea: ${(areas.data??[]).map((z:any)=>[z.suburb,z.city].filter(Boolean).join(", ")).join("; ")||"Not set"}`;return reply(s,x,body,handymanUi(who.handyman.availability_status==="available"))}

  if(action==="MY_JOBS"&&who.handyman){const m=await s.from("job_matches").select("id,job_id,status,offered_at").eq("handyman_id",who.handyman.id).in("status",["offered","accepted"]).order("offered_at",{ascending:false}).limit(10);if(m.error)throw m.error;if(!m.data?.length)return reply(s,x,"You don't have any active job offers or assigned jobs yet.",handymanUi(who.handyman.availability_status==="available"));const ids=[...new Set(m.data.map((z:any)=>z.job_id))];const j=await s.from("jobs").select("id,description,suburb,city,status").in("id",ids);if(j.error)throw j.error;const rows=m.data.map((z:any)=>({...z,job:j.data?.find((q:any)=>q.id===z.job_id)}));const offer=rows.find((z:any)=>z.status==="offered");if(offer)return reply(s,x,`${offer.job?.description??"Job"}\n${[offer.job?.suburb,offer.job?.city].filter(Boolean).join(", ")}`,{type:"buttons",body:"Job offer",buttons:[{id:`ACCEPT:${offer.id}`,title:"Accept"},{id:`DECLINE:${offer.id}`,title:"Decline"},{id:"MY_JOBS",title:"More jobs"}]});const active=rows.find((z:any)=>["assigned","in_progress"].includes(z.job?.status));if(active){const buttons:Button[]=active.job.status==="assigned"?[{id:`START:${active.job.id}`,title:"Start job"},{id:`COMPLETE:${active.job.id}`,title:"Complete"},{id:"GO_OFFLINE",title:"Go offline"}]:[{id:`COMPLETE:${active.job.id}`,title:"Complete job"},{id:"MY_PROFILE",title:"My profile"}];return reply(s,x,`${active.job.description}\n${[active.job.suburb,active.job.city].filter(Boolean).join(", ")}\nStatus: ${active.job.status}`,{type:"buttons",body:"Active job",buttons})}return reply(s,x,rows.map((z:any)=>`• ${z.job?.description??"Job"} — ${z.job?.status??z.status}`).join("\n"),handymanUi(who.handyman.availability_status==="available"))}

  if(action.startsWith("ACCEPT:")&&who.handyman){const matchId=action.slice(7);const m=await s.from("job_matches").select("id,job_id").eq("id",matchId).eq("handyman_id",who.handyman.id).maybeSingle();if(m.error)throw m.error;if(!m.data)return reply(s,x,"That job offer isn't available to this account.",handymanUi(who.handyman.availability_status==="available"));const a=await s.rpc("accept_job_match",{p_match_id:matchId});if(a.error)return reply(s,x,"That job has already been taken or is no longer available.",handymanUi(who.handyman.availability_status==="available"));await s.from("handymen").update({availability_status:"busy",last_active_at:new Date().toISOString()}).eq("id",who.handyman.id);const jc=await getJobAndCustomer(s,m.data.job_id);const customerName=jc.customer.full_name||"Customer";const outbound:Outbound[]=[{to:jc.customer.phone,reply:`Good news — ${who.handyman.full_name} accepted your job: ${jc.job.description}.\nHandyman contact: ${who.handyman.phone}\nYou can now agree the exact address, timing and price directly.`}];return reply(s,x,`Job accepted.\nCustomer: ${customerName}\nContact: ${jc.customer.phone}\nArea: ${[jc.job.suburb,jc.job.city].filter(Boolean).join(", ")}`,{type:"buttons",body:"What next?",buttons:[{id:`START:${jc.job.id}`,title:"Start job"},{id:`COMPLETE:${jc.job.id}`,title:"Complete"},{id:"MY_JOBS",title:"My jobs"}]},{assignment_id:a.data,outbound})}
  if(action.startsWith("DECLINE:")&&who.handyman){const id=action.slice(8);const d=await s.from("job_matches").update({status:"declined",responded_at:new Date().toISOString()}).eq("id",id).eq("handyman_id",who.handyman.id).eq("status","offered");if(d.error)throw d.error;return reply(s,x,"Job declined. I'll keep looking for relevant opportunities.",handymanUi(who.handyman.availability_status==="available"))}
  if(action.startsWith("START:")&&who.handyman){const jobId=action.slice(6);const u=await s.from("job_assignments").update({started_at:new Date().toISOString()}).eq("job_id",jobId).eq("handyman_id",who.handyman.id).is("cancelled_at",null);if(u.error)throw u.error;await s.from("jobs").update({status:"in_progress"}).eq("id",jobId).eq("status","assigned");const jc=await getJobAndCustomer(s,jobId);const outbound:Outbound[]=[{to:jc.customer.phone,reply:`${who.handyman.full_name} marked your job as started: ${jc.job.description}.`}];return reply(s,x,"Job marked as in progress.",{type:"buttons",body:"When you're finished, mark it complete.",buttons:[{id:`COMPLETE:${jobId}`,title:"Complete job"},{id:"MY_JOBS",title:"My jobs"}]},{outbound})}
  if(action.startsWith("COMPLETE:")&&who.handyman){const jobId=action.slice(9);const c=await s.rpc("complete_job_assignment",{p_job_id:jobId,p_handyman_phone:user});if(c.error)return reply(s,x,"I couldn't complete that job. Check My jobs and try again.",handymanUi(false));const jc=await getJobAndCustomer(s,jobId);const outbound:Outbound[]=[{to:jc.customer.phone,reply:`${who.handyman.full_name} marked your job complete: ${jc.job.description}. Please rate the service.`,ui:{type:"list",body:"How was the service?",button:"Rate handyman",rows:[1,2,3,4,5].map(n=>({id:`RATE:${jobId}:${n}`,title:`${n} star${n===1?"":"s"}`}))}}];return reply(s,x,"Job completed. You're available again for new work.",handymanUi(true),{outbound})}

  if(action==="CUSTOMER_JOBS"&&who.customer){const j=await s.from("jobs").select("id,description,suburb,city,status,created_at").eq("customer_id",who.customer.id).order("created_at",{ascending:false}).limit(5);if(j.error)throw j.error;if(!j.data?.length)return reply(s,x,"You haven't requested any jobs yet.",customerUi);const latest=j.data[0];let body=j.data.map((z:any)=>`• ${z.description} — ${z.status==="matching"?"looking for handyman":z.status}`).join("\n");if(latest.status==="matching")return reply(s,x,body,{type:"buttons",body:"Your latest request is still active. I'll keep matching it as suitable handymen become available.",buttons:[{id:`CANCEL:${latest.id}`,title:"Cancel job"},{id:"REQUEST_HELP",title:"New request"},{id:"CUSTOMER_JOBS",title:"Refresh"}]});if(latest.status==="completed")return reply(s,x,body,{type:"list",body:"Rate your latest completed job.",button:"Rate handyman",rows:[1,2,3,4,5].map(n=>({id:`RATE:${latest.id}:${n}`,title:`${n} star${n===1?"":"s"}`}))});return reply(s,x,body,customerUi)}
  if(action.startsWith("CANCEL:")&&who.customer){const jobId=action.slice(7);const u=await s.from("jobs").update({status:"cancelled"}).eq("id",jobId).eq("customer_id",who.customer.id).in("status",["open","matching"]);if(u.error)throw u.error;await s.from("job_matches").update({status:"expired"}).eq("job_id",jobId).eq("status","offered");return reply(s,x,"Job cancelled.",customerUi)}
  if(action.startsWith("RATE:")&&who.customer){const [,jobId,ratingRaw]=action.split(":");const rating=Number(ratingRaw);const r=await s.rpc("rate_completed_job",{p_job_id:jobId,p_customer_phone:user,p_rating:rating,p_comment:null});if(r.error)return reply(s,x,"I couldn't save that rating. Please open My jobs and try again.",customerUi);return reply(s,x,`Thank you. Your ${rating}-star rating has been saved.`,customerUi)}

  if(x.flow==="handyman_onboarding"){
   if(x.state==="capture_name"){if(text.length<2)return reply(s,x,"Please send your full name.");x.context={...x.context,full_name:text};x.state="capture_business";await save(s,x);return reply(s,x,"What's your business name? Reply SKIP if you don't use one.")}
   if(x.state==="capture_business"){x.context={...x.context,business_name:norm(text)==="skip"?null:text};x.state="capture_skills";await save(s,x);return reply(s,x,"Choose your main skill.",await categoryUi(s,"H",0))}
   if(x.state==="capture_skills"){const code=action.startsWith("HSKILL:")?action.slice(7):null;if(!code)return reply(s,x,"Please choose from the service menu.",await categoryUi(s,"H",0));const sk=await s.from("skills").select("code,name").eq("code",code).maybeSingle();if(sk.error||!sk.data)return reply(s,x,"Please choose a valid skill.",await categoryUi(s,"H",0));x.context={...x.context,skill_codes:[sk.data.code]};x.state="capture_location";await save(s,x);return reply(s,x,"Where do you mainly work? Send: Suburb, City, Province. Example: Bellville, Cape Town, Western Cape")}
   if(x.state==="capture_location"){const loc=parseLocation(text);if(!loc)return reply(s,x,"Please send at least Suburb, City. Example: Bellville, Cape Town");const c=x.context as any;if(!c.terms_accepted){x.flow="entry";x.state="choose_role";x.context={};await save(s,x);return reply(s,x,"Please restart provider registration and accept the Terms first.",roleUi)}const r=await s.rpc("onboard_handyman",{p_phone:user,p_full_name:c.full_name,p_business_name:c.business_name??null,p_email:null,p_skill_codes:c.skill_codes??[],p_city:loc.city,p_suburb:loc.suburb,p_province:loc.province});if(r.error)throw r.error;const acceptedAt=new Date().toISOString();const activated=await s.from("handymen").update({registration_status:"active",terms_accepted_at:acceptedAt,terms_version:"2026-08-10",updated_at:acceptedAt}).eq("id",r.data);if(activated.error)throw activated.error;x.flow="ready";x.state="ready";x.context={};x.status="active";await save(s,x);return reply(s,x,"Registration complete. You're offline until you choose ‘I'm available’. Verification is required before receiving jobs. Your Free plan includes 3 job opportunities per month.",handymanUi(false),{handyman_id:r.data})}
  }

  if(x.flow==="customer_job"){
   if(x.state==="capture_job_description"){if(text.length<3)return reply(s,x,"Please describe the problem in a few words.");const inferred=inferSkill(text);x.context={job_description:text,...(inferred?{skill_code:inferred}:{})};if(inferred){const sk=await s.from("skills").select("id,code,name").eq("code",inferred).single();if(sk.error)throw sk.error;x.context={...x.context,skill_id:sk.data.id,skill_name:sk.data.name};x.state="confirm_job_skill";await save(s,x);return reply(s,x,`This looks like ${sk.data.name}. Is that right?`,{type:"buttons",body:`Service: ${sk.data.name}`,buttons:[{id:"CONFIRM_SKILL",title:"Yes"},{id:"CHANGE_SKILL",title:"Change"}]})}x.state="capture_job_skill";await save(s,x);return reply(s,x,"What kind of service is this?",await categoryUi(s,"J",0))}
   if(x.state==="confirm_job_skill"){if(action==="CONFIRM_SKILL"){x.state="capture_job_location";await save(s,x);return reply(s,x,"Where is the job? Send: Suburb, City, Province. Example: Langa, Cape Town, Western Cape")}if(action==="CHANGE_SKILL"){x.state="capture_job_skill";await save(s,x);return reply(s,x,"Choose the closest service.",await categoryUi(s,"J",0))}return reply(s,x,"Please choose Yes or Change.",{type:"buttons",body:`Service: ${(x.context as any).skill_name??"Selected service"}`,buttons:[{id:"CONFIRM_SKILL",title:"Yes"},{id:"CHANGE_SKILL",title:"Change"}]})}
   if(x.state==="capture_job_skill"){const code=action.startsWith("JSKILL:")?action.slice(7):null;if(!code)return reply(s,x,"Please choose from the service menu.",await categoryUi(s,"J",0));const sk=await s.from("skills").select("id,code,name").eq("code",code).maybeSingle();if(sk.error||!sk.data)return reply(s,x,"Please choose a valid service.",await categoryUi(s,"J",0));x.context={...x.context,skill_id:sk.data.id,skill_code:sk.data.code,skill_name:sk.data.name};x.state="capture_job_location";await save(s,x);return reply(s,x,"Where is the job? Send: Suburb, City, Province. Example: Langa, Cape Town, Western Cape")}
   if(x.state==="capture_job_location"){const loc=parseLocation(text);if(!loc)return reply(s,x,"Please send at least Suburb, City. Example: Langa, Cape Town");const c=x.context as any;const cust=await s.from("customers").upsert({phone:user},{onConflict:"phone"}).select("id").single();if(cust.error)throw cust.error;const job=await s.from("jobs").insert({customer_id:cust.data.id,skill_id:c.skill_id,description:c.job_description,suburb:loc.suburb,city:loc.city,province:loc.province,status:"matching",match_attempt_count:1,last_match_attempt_at:new Date().toISOString()}).select("id").single();if(job.error)throw job.error;const cand=await s.rpc("find_job_candidates",{p_job_id:job.data.id,p_limit:5});if(cand.error)throw cand.error;const rows=cand.data??[];let outbound:Outbound[]=[];if(rows.length){const ins=await s.from("job_matches").insert(rows.map((z:any)=>({job_id:job.data.id,handyman_id:z.handyman_id,match_score:z.score,status:"offered"}))).select("id,handyman_id");if(ins.error)throw ins.error;const hids=(ins.data??[]).map((z:any)=>z.handyman_id);const hs=hids.length?await s.from("handymen").select("id,phone,full_name").in("id",hids):{data:[]};outbound=(ins.data??[]).map((m:any)=>{const h=(hs.data??[]).find((z:any)=>z.id===m.handyman_id);return{to:h?.phone,reply:`New ${(c.skill_name??"HandyConnect")} job: ${c.job_description}\nLocation: ${loc.suburb}, ${loc.city}`,ui:{type:"buttons",body:"Are you available for this job?",buttons:[{id:`ACCEPT:${m.id}`,title:"Accept"},{id:`DECLINE:${m.id}`,title:"Decline"},{id:"MY_JOBS",title:"My jobs"}]}}}).filter((z:any)=>z.to)}x.flow="ready";x.state="ready";x.context={};x.status="active";await save(s,x);const msg=rows.length?`Your request is active. I sent it to ${rows.length} available handyman${rows.length===1?"":"s"}. I'll tell you as soon as someone accepts.`:`Your request is active. No suitable handyman is available right now, but I will keep it open and automatically offer it when a matching handyman comes online.`;return reply(s,x,msg,customerUi,{job_id:job.data.id,candidate_count:rows.length,outbound})}
  }

  return resetToMenu(s,x,user);
 }catch(e){console.error(e);return json({error:"internal_error"},500)}
});
