import { createClient } from "@supabase/supabase-js";
type Incoming={channel?:string;external_user_id?:string;message?:string};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS")??"";if(raw){try{const p=JSON.parse(raw);if(typeof p.default==='string')return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const menu={type:'list',body:'Provider profile',button:'Edit profile',rows:[{id:'PROFILE_EDIT_BIO',title:'About me',description:'Short customer-facing introduction'},{id:'PROFILE_EDIT_EXP',title:'Experience',description:'Years working in your trade'},{id:'PROFILE_EDIT_BUSINESS',title:'Business name',description:'Optional trading name'},{id:'HANDYMAN_HOME',title:'Back to dashboard'}]};
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'method_not_allowed'},405);const k=key(),url=Deno.env.get('SUPABASE_URL')??'';if(!k||!url||req.headers.get('apikey')!==k)return json({error:'unauthorized'},401);let input:Incoming;try{input=await req.json()}catch{return json({error:'invalid_json'},400)}const phone=input.external_user_id?.trim(),message=input.message?.trim();if(!phone||!message)return json({error:'missing_input'},400);const s=createClient(url,k,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});try{
 const session=await s.from('conversation_sessions').select('id,state,context').eq('channel',input.channel??'whatsapp').eq('external_user_id',phone).maybeSingle();
 if(session.data?.state==='profile_edit_bio'){const bio=message.trim().slice(0,350);if(bio.length<20)return json({ok:true,reply:'Please write at least 20 characters so customers get a useful introduction.'});await s.from('handymen').update({bio,profile_completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('phone',phone);await s.from('conversation_sessions').update({state:'ready',context:{}}).eq('id',session.data.id);return json({ok:true,reply:'About me updated.',ui:menu})}
 if(session.data?.state==='profile_edit_exp'){const years=Number(message.replace(/[^0-9]/g,''));if(!Number.isInteger(years)||years<0||years>60)return json({ok:true,reply:'Send the number of years only, from 0 to 60. Example: 8'});await s.from('handymen').update({years_experience:years,profile_completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('phone',phone);await s.from('conversation_sessions').update({state:'ready',context:{}}).eq('id',session.data.id);return json({ok:true,reply:`Experience updated to ${years} year${years===1?'':'s'}.`,ui:menu})}
 if(session.data?.state==='profile_edit_business'){const business=message.trim().slice(0,120);await s.from('handymen').update({business_name:business.toLowerCase()==='none'?null:business,profile_completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('phone',phone);await s.from('conversation_sessions').update({state:'ready',context:{}}).eq('id',session.data.id);return json({ok:true,reply:'Business name updated.',ui:menu})}
 if(message.startsWith('PROVIDER_PROFILE:')){const jobId=message.slice(17);const r=await s.rpc('get_assigned_handyman_profile',{p_job_id:jobId,p_customer_phone:phone});if(r.error)throw r.error;if(!r.data?.ok)return json({ok:true,reply:'A provider profile is available after a handyman has been assigned.'});const p=r.data.profile;return json({ok:true,reply:`👤 ${p.full_name}${p.business_name?` · ${p.business_name}`:''}\n${p.verification_status==='verified'?'✓ Identity verified':'Verification pending'}\n⭐ ${p.average_rating??0}/5 · ${p.completed_jobs??0} completed jobs\n🛡 Reliability: ${p.reliability_score??100}/100 (${String(p.reliability_flag??'good').replaceAll('_',' ')})\n🧰 Experience: ${p.years_experience==null?'Not stated':p.years_experience+' years'}\n\n${p.bio||'No introduction added yet.'}\n\nSkills: ${p.skills||'Not listed'}\nService areas: ${p.service_areas||'Not listed'}`,ui:{type:'buttons',body:'Assigned provider',buttons:[{id:`JOB_STATUS:${jobId}`,title:'Job status'}]}})}
 const h=await s.from('handymen').select('id,full_name,business_name,bio,years_experience,verification_status,average_rating,completed_jobs,reliability_score,reliability_flag').eq('phone',phone).maybeSingle();
 if(message==='PROFILE_EDIT'||message==='PROFILE_HOME'){if(!h.data)return json({handled:false});return json({ok:true,reply:`${h.data.full_name}${h.data.business_name?` · ${h.data.business_name}`:''}\nVerification: ${h.data.verification_status}\nRating: ${h.data.average_rating??0}/5 · ${h.data.completed_jobs??0} jobs\nReliability: ${h.data.reliability_score??100}/100\nExperience: ${h.data.years_experience==null?'Not set':h.data.years_experience+' years'}\nAbout: ${h.data.bio||'Not set'}`,ui:menu})}
 if(message==='PROFILE_EDIT_BIO'){if(!h.data)return json({handled:false});await s.from('conversation_sessions').upsert({channel:input.channel??'whatsapp',external_user_id:phone,state:'profile_edit_bio',context:{}},{onConflict:'channel,external_user_id'});return json({ok:true,reply:'Write a short introduction for customers (20–350 characters). Mention the work you specialise in and what customers can expect.'})}
 if(message==='PROFILE_EDIT_EXP'){if(!h.data)return json({handled:false});await s.from('conversation_sessions').upsert({channel:input.channel??'whatsapp',external_user_id:phone,state:'profile_edit_exp',context:{}},{onConflict:'channel,external_user_id'});return json({ok:true,reply:'How many years of hands-on experience do you have? Send a number from 0 to 60.'})}
 if(message==='PROFILE_EDIT_BUSINESS'){if(!h.data)return json({handled:false});await s.from('conversation_sessions').upsert({channel:input.channel??'whatsapp',external_user_id:phone,state:'profile_edit_business',context:{}},{onConflict:'channel,external_user_id'});return json({ok:true,reply:'Send your business/trading name, or type none if you work under your own name.'})}
 return json({handled:false});
}catch(e){console.error(e);return json({error:'profile_router_failed'},500)}});