import { createClient } from "@supabase/supabase-js";
type Incoming={channel?:string;external_user_id?:string;external_message_id?:string;message?:string;media?:{id:string;type:string;mime_type?:string;filename?:string}};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS")??"";if(raw){try{const p=JSON.parse(raw);if(typeof p.default==='string')return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
function parseLocation(t:string){const p=t.split(',').map(x=>x.trim()).filter(Boolean);return p.length<2?null:{suburb:p[0],city:p[1],province:p[2]??null}}
const urgencyUi={type:'buttons',body:'How soon do you need help?',buttons:[{id:'JI_URGENT',title:'As soon as possible'},{id:'JI_TODAY',title:'Today'},{id:'JI_FLEXIBLE',title:'Flexible'}]};
const timeUi={type:'list',body:'What appointment window suits you best?',button:'Choose time',rows:[{id:'JI_TIME_MORNING',title:'Morning',description:'08:00–12:00'},{id:'JI_TIME_AFTERNOON',title:'Afternoon',description:'12:00–17:00'},{id:'JI_TIME_EVENING',title:'Evening',description:'17:00–20:00'},{id:'JI_TIME_ANY',title:'Any time',description:'No preference'}]};
const materialsUi={type:'buttons',body:'Do you already have the parts or materials?',buttons:[{id:'JI_MAT_YES',title:'Yes'},{id:'JI_MAT_NO',title:'No'},{id:'JI_MAT_UNSURE',title:'Not sure'}]};
const photoUi={type:'buttons',body:'A photo can help the handyman understand the job before accepting.',buttons:[{id:'JI_SKIP_PHOTO',title:'Skip photo'}]};
async function offer(s:any,job:any,skillName:string){const cand=await s.rpc('find_job_candidates',{p_job_id:job.id,p_limit:5});if(cand.error)throw cand.error;const rows=cand.data??[];if(!rows.length)return[];const ins=await s.from('job_matches').insert(rows.map((z:any)=>({job_id:job.id,handyman_id:z.handyman_id,match_score:z.score,status:'offered'}))).select('id,handyman_id');if(ins.error)throw ins.error;const hs=await s.from('handymen').select('id,phone').in('id',(ins.data??[]).map((z:any)=>z.handyman_id));return(ins.data??[]).map((m:any)=>{const h=(hs.data??[]).find((z:any)=>z.id===m.handyman_id);return{to:h?.phone,reply:`New ${skillName} job: ${job.description}\nLocation: ${job.suburb}, ${job.city}\nUrgency: ${job.urgency}\nPreferred time: ${job.appointment_window}\nMaterials: ${job.materials_status}${job.photo_count?`\nPhotos attached: ${job.photo_count}`:''}`,ui:{type:'buttons',body:'Are you available for this job?',buttons:[{id:`ACCEPT:${m.id}`,title:'Accept'},{id:`DECLINE:${m.id}`,title:'Decline'},{id:'MY_JOBS',title:'My jobs'}]}}}).filter((x:any)=>x.to)}
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'method_not_allowed'},405);const k=key(),url=Deno.env.get('SUPABASE_URL')??'';if(!k||!url||req.headers.get('apikey')!==k)return json({error:'unauthorized'},401);let input:Incoming;try{input=await req.json()}catch{return json({error:'invalid_json'},400)}const phone=input.external_user_id?.trim(),msg=input.message?.trim()??'';if(!phone)return json({handled:false});const s=createClient(url,k,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});try{let q=await s.from('conversation_sessions').select('id,state,context').eq('channel',input.channel??'whatsapp').eq('external_user_id',phone).maybeSingle();let session=q.data;
 if(msg==='REQUEST_HELP'){if(!session){const n=await s.from('conversation_sessions').insert({channel:input.channel??'whatsapp',external_user_id:phone,flow:'job_intake',state:'ji_description',context:{}}).select('id,state,context').single();session=n.data}else await s.from('conversation_sessions').update({flow:'job_intake',state:'ji_description',context:{}}).eq('id',session.id);return json({handled:true,reply:'Tell me what needs fixing. A short description is enough.'})}
 if(!session||!String(session.state).startsWith('ji_'))return json({handled:false});let c:any=session.context??{};
 if(session.state==='ji_description'){if(msg.length<3)return json({handled:true,reply:'Please describe the problem in a few words.'});c={description:msg};await s.from('conversation_sessions').update({state:'ji_location',context:c}).eq('id',session.id);return json({handled:true,reply:'Where is the job? Send: Suburb, City, Province. Example: Langa, Cape Town, Western Cape'})}
 if(session.state==='ji_location'){const loc=parseLocation(msg);if(!loc)return json({handled:true,reply:'Please send at least Suburb, City. Example: Langa, Cape Town'});c={...c,...loc};await s.from('conversation_sessions').update({state:'ji_urgency',context:c}).eq('id',session.id);return json({handled:true,reply:'Got it.',ui:urgencyUi})}
 if(session.state==='ji_urgency'){const map:any={JI_URGENT:'urgent',JI_TODAY:'today',JI_FLEXIBLE:'flexible'};if(!map[msg])return json({handled:true,reply:'Choose how soon you need help.',ui:urgencyUi});c={...c,urgency:map[msg]};await s.from('conversation_sessions').update({state:'ji_time',context:c}).eq('id',session.id);return json({handled:true,reply:'When should the handyman come?',ui:timeUi})}
 if(session.state==='ji_time'){const map:any={JI_TIME_MORNING:'morning',JI_TIME_AFTERNOON:'afternoon',JI_TIME_EVENING:'evening',JI_TIME_ANY:'any_time'};if(!map[msg])return json({handled:true,reply:'Choose an appointment window.',ui:timeUi});c={...c,appointment_window:map[msg]};await s.from('conversation_sessions').update({state:'ji_materials',context:c}).eq('id',session.id);return json({handled:true,reply:'One more useful detail.',ui:materialsUi})}
 if(session.state==='ji_materials'){const map:any={JI_MAT_YES:'customer_has_materials',JI_MAT_NO:'materials_needed',JI_MAT_UNSURE:'unsure'};if(!map[msg])return json({handled:true,reply:'Choose the closest option.',ui:materialsUi});c={...c,materials_status:map[msg]};await s.from('conversation_sessions').update({state:'ji_photo',context:c}).eq('id',session.id);return json({handled:true,reply:'You can now send one photo of the problem, or skip it.',ui:photoUi})}
 if(session.state==='ji_photo'){if(input.media?.id)c={...c,photo:{media_id:input.media.id,media_type:input.media.type,mime_type:input.media.mime_type??null,file_name:input.media.filename??null}};else if(msg!=='JI_SKIP_PHOTO')return json({handled:true,reply:'Send a photo, or tap Skip photo.',ui:photoUi});const skill=await s.rpc('infer_skill_for_job',{p_description:c.description});let skillId=skill.data?.skill_id??null,skillName=skill.data?.skill_name??'Handyman';if(!skillId){const fallback=await s.from('skills').select('id,name').eq('code','general_handyman').maybeSingle();skillId=fallback.data?.id;skillName=fallback.data?.name??skillName}const cust=await s.from('customers').upsert({phone},{onConflict:'phone'}).select('id').single();if(cust.error)throw cust.error;const job=await s.from('jobs').insert({customer_id:cust.data.id,skill_id:skillId,description:c.description,suburb:c.suburb,city:c.city,province:c.province,urgency:c.urgency,appointment_window:c.appointment_window,materials_status:c.materials_status,status:'matching',match_attempt_count:1,last_match_attempt_at:new Date().toISOString()}).select('id,description,suburb,city,urgency,appointment_window,materials_status').single();if(job.error)throw job.error;let photoCount=0;if(c.photo){const a=await s.from('job_attachments').insert({job_id:job.data.id,customer_id:cust.data.id,...c.photo});if(a.error)throw a.error;photoCount=1}const outbound=await offer(s,{...job.data,photo_count:photoCount},skillName);await s.from('conversation_sessions').update({flow:'ready',state:'ready',context:{}}).eq('id',session.id);return json({handled:true,job_id:job.data.id,reply:outbound.length?`Your request is active. I sent the full job details to ${outbound.length} matching handyman${outbound.length===1?'':'s'}. I'll tell you as soon as someone accepts.`:'Your request is active. No suitable handyman is available right now, so I’ll keep matching automatically.',outbound})}
 return json({handled:false});}catch(e){console.error(e);return json({error:'job_intake_failed'},500)}});