import { createClient } from "@supabase/supabase-js";
type Incoming={channel?:string;external_user_id?:string;message?:string};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const p=JSON.parse(raw);if(typeof p.default==="string"&&p.default)return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const buttons=(body:string,buttons:any[])=>({type:"buttons",body,buttons:buttons.slice(0,3)});
Deno.serve(async req=>{if(req.method!=="POST")return json({handled:false});const k=key(),url=Deno.env.get("SUPABASE_URL")??"";if(!k||req.headers.get("apikey")!==k)return json({error:"unauthorized"},401);let input:Incoming;try{input=await req.json()}catch{return json({handled:false})}const phone=input.external_user_id?.trim(),m=input.message?.trim()??"";if(!phone||!m)return json({handled:false});const s=createClient(url,k,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});try{
if(m==="H_VERIFY"||m==="H_SUBMIT_ID"){const h=await s.from("handymen").select("id,verification_status").eq("phone",phone).maybeSingle();if(!h.data)return json({handled:false});if(m==="H_SUBMIT_ID"&&h.data.verification_status==="verified")return json({handled:true,reply:"You're already verified and eligible for jobs.",ui:buttons("Verification complete",[{id:"H_AVAIL",title:"Go available"},{id:"HANDYMAN_HOME",title:"Dashboard"}])});return json({handled:false});}
if(m.startsWith("ACCEPT:")||m.startsWith("DECLINE:")){const id=m.split(":")[1];const q=await s.from("job_matches").select("id,job_id,status,offer_expires_at,handyman_id").eq("id",id).maybeSingle();const h=await s.from("handymen").select("id,active_job_id,verification_status").eq("phone",phone).maybeSingle();if(!h.data)return json({handled:false});if(!q.data||q.data.handyman_id!==h.data.id||q.data.status!=="offered"||(q.data.offer_expires_at&&new Date(q.data.offer_expires_at)<=new Date()))return json({handled:true,reply:"That job offer is no longer active. I've kept you in the current flow instead of applying the old action.",ui:buttons("What next?",[{id:"H_NEW",title:"Current offers"},{id:"H_CURRENT",title:"Current job"},{id:"HANDYMAN_HOME",title:"Dashboard"}])});if(m.startsWith("ACCEPT:")&&h.data.verification_status!=="verified")return json({handled:true,reply:"That offer is still visible, but identity verification must be completed before you can accept jobs.",ui:buttons("Finish verification",[{id:"H_VERIFY",title:"Verify now"},{id:"H_NEW",title:"Back to jobs"},{id:"HANDYMAN_HOME",title:"Dashboard"}])});return json({handled:false});}
if(m.startsWith("QUOTE_ACCEPT:")||m.startsWith("QUOTE_REJECT:")){const id=m.split(":")[1];const q=await s.from("job_quotes").select("id,job_id,status").eq("id",id).maybeSingle();const c=await s.from("customers").select("id").eq("phone",phone).maybeSingle();if(!c.data)return json({handled:false});if(!q.data||q.data.status!=="proposed")return json({handled:true,reply:"That quote is no longer waiting for your response. I've opened the current job path instead.",ui:buttons("Job status",[{id:"CUSTOMER_JOBS",title:"My jobs"},{id:"HOME",title:"Home"}])});const j=await s.from("jobs").select("customer_id,status").eq("id",q.data.job_id).maybeSingle();if(!j.data||j.data.customer_id!==c.data.id||!["assigned","in_progress"].includes(j.data.status))return json({handled:true,reply:"That quote belongs to a job that has already moved on.",ui:buttons("Job status",[{id:"CUSTOMER_JOBS",title:"My jobs"},{id:"HOME",title:"Home"}])});return json({handled:false});}
const jobActionPrefixes=["ARRIVED:","COMPLETE:","CONFIRM_START:","CONFIRM_COMPLETE:","CANCEL_CONFIRM:"];
const p=jobActionPrefixes.find(x=>m.startsWith(x));if(p){const id=m.slice(p.length);const j=await s.from("jobs").select("id,customer_id,status").eq("id",id).maybeSingle();if(!j.data)return json({handled:true,reply:"That job no longer exists or is no longer available from this old button.",ui:buttons("Return safely",[{id:"CUSTOMER_JOBS",title:"My jobs"},{id:"H_CURRENT",title:"Current job"},{id:"HOME",title:"Home"}])});if(p==="CONFIRM_START:"&&j.data.status!=="assigned")return json({handled:true,reply:`That start button is outdated. The job is currently ${j.data.status.replaceAll("_"," ")}.`,ui:buttons("Current status",[{id:`CJOB:${id}`,title:"Open job"},{id:"CUSTOMER_JOBS",title:"My jobs"}])});if(p==="CONFIRM_COMPLETE:"&&j.data.status!=="in_progress")return json({handled:true,reply:`That completion button is outdated. The job is currently ${j.data.status.replaceAll("_"," ")}.`,ui:buttons("Current status",[{id:`CJOB:${id}`,title:"Open job"},{id:"CUSTOMER_JOBS",title:"My jobs"}])});if((p==="ARRIVED:"||p==="COMPLETE:")&&!["assigned","in_progress"].includes(j.data.status))return json({handled:true,reply:`That provider action is outdated. The job is currently ${j.data.status.replaceAll("_"," ")}.`,ui:buttons("Current status",[{id:"H_CURRENT",title:"Current job"},{id:"H_HISTORY",title:"History"},{id:"HANDYMAN_HOME",title:"Dashboard"}])});if(p==="CANCEL_CONFIRM:"&&!['open','matching'].includes(j.data.status))return json({handled:true,reply:`That cancellation button is outdated. The job is currently ${j.data.status.replaceAll("_"," ")}.`,ui:buttons("Current status",[{id:`CJOB:${id}`,title:"Open job"},{id:"CUSTOMER_JOBS",title:"My jobs"}])});return json({handled:false});}
return json({handled:false});}catch(e){console.error(e);return json({handled:false})}});
