import { createClient } from "@supabase/supabase-js";

type Incoming={channel?:"whatsapp"|"test"|"admin";external_user_id?:string;external_message_id?:string;message?:string};
type Ui={type:"buttons";body:string;buttons:{id:string;title:string}[]}|{type:"list";body:string;button:string;rows:{id:string;title:string;description?:string}[]};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const p=JSON.parse(raw);if(typeof p.default==="string"&&p.default)return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const norm=(s:string)=>s.trim().toLowerCase();
function parseLocation(text:string){const p=text.split(",").map(x=>x.trim()).filter(Boolean);return p.length<2?null:{suburb:p[0],city:p[1],province:p[2]??null}}
async function delegate(url:string,k:string,input:Incoming,override?:string){const r=await fetch(`${url}/functions/v1/conversation-engine`,{method:"POST",headers:{apikey:k,"content-type":"application/json"},body:JSON.stringify({...input,message:override??input.message})});return{status:r.status,body:await r.json().catch(()=>({error:"invalid_engine_response"}))}}
function dashboardUi():Ui{return{type:"list",body:"Handyman dashboard",button:"Open dashboard",rows:[{id:"H_AVAIL",title:"Availability",description:"Go online or offline"},{id:"H_JOBS",title:"My jobs",description:"Offers and active jobs"},{id:"H_PROFILE",title:"My profile",description:"Skills, areas and trust"},{id:"H_SKILLS",title:"My skills",description:"Add another service"},{id:"H_AREAS",title:"Service areas",description:"Where you accept work"},{id:"H_PLAN",title:"Plan & opportunities",description:"Free/paid access and usage"}]}}
function availabilityUi():Ui{return{type:"list",body:"How long are you available for new jobs?",button:"Set availability",rows:[{id:"H_AVAIL:2",title:"Available 2 hours"},{id:"H_AVAIL:4",title:"Available 4 hours"},{id:"H_AVAIL:8",title:"Available 8 hours"},{id:"H_AVAIL:12",title:"Available today"},{id:"H_OFFLINE",title:"Go offline"}]}}
const categoryPages=[["appliance_repair","plumbing","electrical","general_handyman","carpentry","painting","locksmith","tiling","aircon_hvac"],["solar_inverter","cctv_security","gates_garage_doors","roofing","waterproofing","ceilings_drywall","flooring","glazing_windows","welding_metalwork"],["gardening_landscaping","pool_maintenance","paving","gutters","pest_control","furniture_assembly","moving_small_jobs"]];
async function skillMenu(s:any,page=0):Promise<Ui>{const {data}=await s.from("skills").select("code,name").eq("active",true);const map=new Map((data??[]).map((z:any)=>[z.code,z]));const rows=(categoryPages[page]??categoryPages[0]).map(c=>map.get(c)).filter(Boolean).map((z:any)=>({id:`H_ADD_SKILL:${z.code}`,title:z.name}));if(page<2)rows.push({id:`H_SKILL_PAGE:${page+1}`,title:"More services"});if(page>0)rows.push({id:`H_SKILL_PAGE:${page-1}`,title:"Previous services"});return{type:"list",body:"Add a service you can genuinely perform.",button:"Choose service",rows:rows.slice(0,10)}}

Deno.serve(async(req)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const k=key();if(!k||req.headers.get("apikey")!==k)return json({error:"unauthorized"},401);const s=createClient(Deno.env.get("SUPABASE_URL")??"",k,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});let input:Incoming;try{input=await req.json()}catch{return json({error:"invalid_json"},400)}const phone=input.external_user_id?.trim(),message=input.message?.trim();if(!phone||!message)return json({error:"missing_input"},400);const url=Deno.env.get("SUPABASE_URL")??"";try{
 const hq=await s.from("handymen").select("id,full_name,business_name,verification_status,average_rating,completed_jobs,availability_status,available_until").eq("phone",phone).maybeSingle();if(hq.error)throw hq.error;const h=hq.data;if(!h){const d=await delegate(url,k,input);return json(d.body,d.status)}
 const session=await s.from("conversation_sessions").select("id,state,context").eq("channel",input.channel??"whatsapp").eq("external_user_id",phone).maybeSingle();
 if(session.data?.state==="handyman_router_add_area"){const loc=parseLocation(message);if(!loc)return json({ok:true,reply:"Please send Suburb, City, Province. Example: Bellville, Cape Town, Western Cape"});await s.from("conversation_sessions").update({state:"handyman_router_area_scope",context:{pending_area:loc}}).eq("id",session.data.id);return json({ok:true,reply:`Area: ${loc.suburb}, ${loc.city}. How broadly do you work?`,ui:{type:"buttons",body:"Service coverage",buttons:[{id:"H_AREA_SCOPE:suburb",title:"This suburb"},{id:"H_AREA_SCOPE:city",title:"Whole city"},{id:"H_AREA_SCOPE:province",title:"Province"}]}})}
 if(message.startsWith("H_AREA_SCOPE:")&&session.data?.state==="handyman_router_area_scope"){const coverage=message.split(":")[1];const loc=session.data.context?.pending_area;if(!loc||!["suburb","city","province"].includes(coverage))return json({ok:true,reply:"That area setup expired. Open Service areas and try again.",ui:dashboardUi()});const ins=await s.from("service_areas").insert({handyman_id:h.id,suburb:loc.suburb,city:loc.city,province:loc.province,coverage_type:coverage});if(ins.error&&ins.error.code!=="23505")throw ins.error;await s.from("conversation_sessions").update({state:"ready",context:{}}).eq("id",session.data.id);return json({ok:true,reply:`Service area added: ${loc.suburb}, ${loc.city} (${coverage}).`,ui:dashboardUi()})}
 if(["hi","hello","menu","start","HANDYMAN_HOME"].includes(message)||["hi","hello","menu","start"].includes(norm(message))){const until=h.available_until?new Date(h.available_until).toLocaleString("en-ZA",{timeZone:"Africa/Johannesburg",hour:"2-digit",minute:"2-digit",day:"2-digit",month:"short"}):null;return json({ok:true,reply:`Welcome back, ${h.full_name}.\nAvailability: ${h.availability_status}${until?` until ${until}`:""}\nRating: ${h.average_rating??0}/5 · ${h.completed_jobs??0} completed\nVerification: ${h.verification_status}`,ui:dashboardUi()})}
 if(message==="H_AVAIL")return json({ok:true,reply:`Current availability: ${h.availability_status}.`,ui:availabilityUi()});
 if(message.startsWith("H_AVAIL:")){const hours=Math.max(1,Math.min(12,Number(message.split(":")[1])||8));const r=await s.rpc("set_handyman_availability",{p_phone:phone,p_status:"available",p_hours:hours});if(r.error)throw r.error;const waiting=await s.rpc("offer_waiting_jobs_to_handyman",{p_phone:phone,p_limit:5});if(waiting.error)throw waiting.error;const jobs=waiting.data??[];if(jobs.length){const j=jobs[0];return json({ok:true,reply:`You're available for ${hours} hours. I found ${jobs.length} waiting job${jobs.length===1?"":"s"} matching your profile.\n\n${j.skill_name}: ${j.description}\n${j.suburb}, ${j.city}`,ui:{type:"buttons",body:"Would you like this job?",buttons:[{id:`ACCEPT:${j.match_id}`,title:"Accept"},{id:`DECLINE:${j.match_id}`,title:"Decline"},{id:"MY_JOBS",title:"My jobs"}]}})}return json({ok:true,reply:`You're available for the next ${hours} hours. Relevant jobs can now be offered to you automatically.`,ui:dashboardUi()})}
 if(message==="H_OFFLINE"){const r=await s.rpc("set_handyman_availability",{p_phone:phone,p_status:"offline",p_hours:8});if(r.error)throw r.error;return json({ok:true,reply:"You're offline. You won't receive new job offers until you go available again.",ui:dashboardUi()})}
 if(message==="H_JOBS"){const d=await delegate(url,k,input,"MY_JOBS");return json(d.body,d.status)}
 if(message==="H_PROFILE"){const areas=await s.from("service_areas").select("suburb,city,province,coverage_type").eq("handyman_id",h.id);const hs=await s.from("handyman_skills").select("skill_id").eq("handyman_id",h.id);const ids=(hs.data??[]).map((x:any)=>x.skill_id);const skills=ids.length?await s.from("skills").select("id,name").in("id",ids):{data:[]};return json({ok:true,reply:`${h.full_name}${h.business_name?` · ${h.business_name}`:""}\nVerification: ${h.verification_status}\nRating: ${h.average_rating??0}/5 (${h.completed_jobs??0} completed)\nSkills: ${(skills.data??[]).map((x:any)=>x.name).join(", ")||"None"}\nAreas: ${(areas.data??[]).map((a:any)=>`${a.suburb}, ${a.city} (${a.coverage_type})`).join("; ")||"None"}`,ui:dashboardUi()})}
 if(message==="H_SKILLS")return json({ok:true,reply:"Your profile can contain multiple genuine skills.",ui:await skillMenu(s,0)});
 if(message.startsWith("H_SKILL_PAGE:"))return json({ok:true,reply:"Choose another service.",ui:await skillMenu(s,Number(message.split(":")[1])||0)});
 if(message.startsWith("H_ADD_SKILL:")){const code=message.slice(12);const sk=await s.from("skills").select("id,name").eq("code",code).maybeSingle();if(sk.error||!sk.data)return json({ok:true,reply:"That service is unavailable.",ui:await skillMenu(s,0)});const ins=await s.from("handyman_skills").insert({handyman_id:h.id,skill_id:sk.data.id});if(ins.error&&ins.error.code!=="23505")throw ins.error;return json({ok:true,reply:`${sk.data.name} added to your profile.`,ui:dashboardUi()})}
 if(message==="H_AREAS"){const a=await s.from("service_areas").select("suburb,city,province,coverage_type").eq("handyman_id",h.id);return json({ok:true,reply:(a.data??[]).length?`Your service areas:\n${(a.data??[]).map((x:any)=>`• ${x.suburb}, ${x.city} — ${x.coverage_type}`).join("\n")}`:"You haven't added a service area yet.",ui:{type:"buttons",body:"Service areas",buttons:[{id:"H_ADD_AREA",title:"Add area"},{id:"HANDYMAN_HOME",title:"Dashboard"}]}})}
 if(message==="H_ADD_AREA"){if(session.data?.id)await s.from("conversation_sessions").update({state:"handyman_router_add_area",context:{}}).eq("id",session.data.id);return json({ok:true,reply:"Send a place you work in as: Suburb, City, Province. Example: Bellville, Cape Town, Western Cape"})}
 if(message==="H_PLAN"){const e=await s.from("entitlements").select("entitlement_type,status,valid_from,valid_until").eq("handyman_id",h.id).eq("status","active");const usage=await s.from("job_matches").select("id",{count:"exact",head:true}).eq("handyman_id",h.id).gte("offered_at",new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString());const pro=(e.data??[]).some((x:any)=>x.entitlement_type==="pro_access"&&(!x.valid_until||new Date(x.valid_until)>new Date()));const used=usage.count??0;return json({ok:true,reply:pro?`Plan: Pro\nJob opportunities this month: ${used}\nAccess: active`:`Plan: Free\nOpportunities used this month: ${used}/3\nRemaining: ${Math.max(0,3-used)}`,ui:dashboardUi()})}
 const d=await delegate(url,k,input);return json(d.body,d.status);
}catch(e){console.error(e);return json({error:"internal_error"},500)}});
