import { createClient } from "@supabase/supabase-js";

type Incoming={channel?:"whatsapp"|"test"|"admin";external_user_id?:string;external_message_id?:string;message?:string};
type Ui={type:"buttons";body:string;buttons:{id:string;title:string}[]}|{type:"list";body:string;button:string;rows:{id:string;title:string;description?:string}[]};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
function secretKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const p=JSON.parse(raw);if(typeof p.default==="string"&&p.default)return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const norm=(s:string)=>s.trim().toLowerCase();
function parseLocation(text:string){const p=text.split(",").map(x=>x.trim()).filter(Boolean);return p.length<2?null:{suburb:p[0],city:p[1],province:p[2]??null}}
const homeUi:Ui={type:"buttons",body:"What would you like to do?",buttons:[{id:"REQUEST_HELP",title:"Request help"},{id:"CUSTOMER_JOBS",title:"My jobs"}]};
function jobMenu(jobId:string,status:string):Ui{return{type:"list",body:`Job options · ${status}`,button:"Manage job",rows:[{id:`JOB_STATUS:${jobId}`,title:"Check status"},{id:`EDIT_JOB:${jobId}`,title:"Edit request"},{id:"NEW_REQUEST",title:"New request"},{id:`CANCEL:${jobId}`,title:"Cancel request"},{id:"HOME",title:"Home"}]}}
async function delegate(url:string,key:string,input:Incoming,override?:string){const r=await fetch(`${url}/functions/v1/conversation-engine`,{method:"POST",headers:{apikey:key,"content-type":"application/json"},body:JSON.stringify({...input,message:override??input.message})});const body=await r.json().catch(()=>({error:"invalid_engine_response"}));return{ok:r.ok,status:r.status,body}}
async function customer(s:any,phone:string){const {data,error}=await s.from("customers").select("id,phone,full_name").eq("phone",phone).maybeSingle();if(error)throw error;return data}
async function latestJob(s:any,customerId:string){const {data,error}=await s.from("jobs").select("id,description,suburb,city,province,status,skill_id,created_at").eq("customer_id",customerId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data}
async function jobOwned(s:any,customerId:string,jobId:string){const {data,error}=await s.from("jobs").select("id,description,suburb,city,province,status,skill_id,created_at").eq("id",jobId).eq("customer_id",customerId).maybeSingle();if(error)throw error;return data}
async function skillName(s:any,id:number|null){if(!id)return"Uncategorised";const {data}=await s.from("skills").select("name").eq("id",id).maybeSingle();return data?.name??"Service"}
async function jobCard(s:any,job:any){const skill=await skillName(s,job.skill_id);let status="Searching for a handyman";let extra="Your request stays active until matched, cancelled or completed.";if(job.status==="assigned"||job.status==="in_progress"||job.status==="completed"){const a=await s.from("job_assignments").select("handyman_id").eq("job_id",job.id).maybeSingle();if(a.data){const h=await s.from("handymen").select("full_name,phone,average_rating").eq("id",a.data.handyman_id).maybeSingle();if(h.data)extra=`Handyman: ${h.data.full_name}\nContact: ${h.data.phone}\nRating: ${h.data.average_rating??0}/5`;}status=job.status==="assigned"?"Handyman assigned":job.status==="in_progress"?"Work in progress":"Completed"}if(job.status==="cancelled")status="Cancelled";return`🔧 ${skill}\n${job.description}\n📍 ${[job.suburb,job.city].filter(Boolean).join(", ")}\nStatus: ${status}\n\n${extra}`}
async function rematch(s:any,job:any){if(job.status!=="matching"&&job.status!=="open")return[];await s.from("jobs").update({match_attempt_count:(job.match_attempt_count??0)+1,last_match_attempt_at:new Date().toISOString()}).eq("id",job.id);const cand=await s.rpc("find_job_candidates",{p_job_id:job.id,p_limit:5});if(cand.error)throw cand.error;const rows=cand.data??[];if(!rows.length)return[];const existing=await s.from("job_matches").select("handyman_id").eq("job_id",job.id);const used=new Set((existing.data??[]).map((z:any)=>z.handyman_id));const fresh=rows.filter((z:any)=>!used.has(z.handyman_id));if(!fresh.length)return[];const ins=await s.from("job_matches").insert(fresh.map((z:any)=>({job_id:job.id,handyman_id:z.handyman_id,match_score:z.score,status:"offered"}))).select("id,handyman_id");if(ins.error)throw ins.error;const hs=await s.from("handymen").select("id,phone").in("id",(ins.data??[]).map((z:any)=>z.handyman_id));const skill=await skillName(s,job.skill_id);return(ins.data??[]).map((m:any)=>{const h=(hs.data??[]).find((z:any)=>z.id===m.handyman_id);return{to:h?.phone,reply:`New ${skill} job: ${job.description}\nLocation: ${job.suburb}, ${job.city}`,ui:{type:"buttons",body:"Are you available for this job?",buttons:[{id:`ACCEPT:${m.id}`,title:"Accept"},{id:`DECLINE:${m.id}`,title:"Decline"},{id:"MY_JOBS",title:"My jobs"}]}}}).filter((z:any)=>z.to)}
const categoryPages=[["appliance_repair","plumbing","electrical","general_handyman","carpentry","painting","locksmith","tiling","aircon_hvac"],["solar_inverter","cctv_security","gates_garage_doors","roofing","waterproofing","ceilings_drywall","flooring","glazing_windows","welding_metalwork"],["gardening_landscaping","pool_maintenance","paving","gutters","pest_control","furniture_assembly","moving_small_jobs"]];
async function editSkillUi(s:any,jobId:string,page=0):Promise<Ui>{const {data}=await s.from("skills").select("code,name").eq("active",true);const map=new Map((data??[]).map((z:any)=>[z.code,z]));const rows=(categoryPages[page]??categoryPages[0]).map(c=>map.get(c)).filter(Boolean).map((z:any)=>({id:`ESKILL:${jobId}:${z.code}`,title:z.name}));if(page<2)rows.push({id:`ESVCPAGE:${jobId}:${page+1}`,title:"More services"});if(page>0)rows.push({id:`ESVCPAGE:${jobId}:${page-1}`,title:"Previous services"});return{type:"list",body:"Choose the correct service.",button:"Choose service",rows:rows.slice(0,10)}}

Deno.serve(async(req)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const key=secretKey();if(!key||req.headers.get("apikey")!==key)return json({error:"unauthorized"},401);const s=createClient(Deno.env.get("SUPABASE_URL")??"",key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});let input:Incoming;try{input=await req.json()}catch{return json({error:"invalid_json"},400)}const phone=input.external_user_id?.trim(),message=input.message?.trim();if(!phone||!message)return json({error:"missing_input"},400);const url=Deno.env.get("SUPABASE_URL")??"";try{const c=await customer(s,phone);const session=await s.from("conversation_sessions").select("id,state,context").eq("channel",input.channel??"whatsapp").eq("external_user_id",phone).maybeSingle();if(c&&session.data?.state==="router_edit_location"){const loc=parseLocation(message);if(!loc)return json({ok:true,reply:"Please send Suburb, City, Province. Example: Langa, Cape Town, Western Cape"});const jobId=session.data.context?.editing_job_id;const job=await jobOwned(s,c.id,jobId);if(!job)return json({ok:true,reply:"I couldn't find that job.",ui:homeUi});await s.from("jobs").update({...loc,status:"matching"}).eq("id",jobId);await s.from("job_matches").update({status:"expired"}).eq("job_id",jobId).eq("status","offered");await s.from("conversation_sessions").update({state:"ready",context:{}}).eq("id",session.data.id);const updated=await jobOwned(s,c.id,jobId);const outbound=await rematch(s,updated);return json({ok:true,reply:await jobCard(s,updated),ui:jobMenu(jobId,updated.status),outbound})}
if(c&&["hi","hello","menu","start"].includes(norm(message))){const j=await latestJob(s,c.id);if(j&&!["completed","cancelled","expired"].includes(j.status))return json({ok:true,reply:await jobCard(s,j),ui:jobMenu(j.id,j.status)});}
if(c&&message==="CUSTOMER_JOBS"){const j=await latestJob(s,c.id);if(!j)return json({ok:true,reply:"You don't have any jobs yet.",ui:homeUi});return json({ok:true,reply:await jobCard(s,j),ui:jobMenu(j.id,j.status)})}
if(c&&message.startsWith("JOB_STATUS:")){const id=message.slice(11);const j=await jobOwned(s,c.id,id);if(!j)return json({ok:true,reply:"I couldn't find that job.",ui:homeUi});const outbound=await rematch(s,j);const fresh=await jobOwned(s,c.id,id);return json({ok:true,reply:await jobCard(s,fresh),ui:jobMenu(id,fresh.status),outbound})}
if(c&&message.startsWith("EDIT_JOB:")){const id=message.slice(9);const j=await jobOwned(s,c.id,id);if(!j)return json({ok:true,reply:"I couldn't find that job.",ui:homeUi});return json({ok:true,reply:await jobCard(s,j),ui:{type:"buttons",body:"What would you like to change?",buttons:[{id:`EDITLOC:${id}`,title:"Location"},{id:`EDITSVC:${id}`,title:"Service"},{id:`JOB_STATUS:${id}`,title:"Back"}]}})}
if(c&&message.startsWith("EDITLOC:")){const id=message.slice(8);const j=await jobOwned(s,c.id,id);if(!j)return json({ok:true,reply:"I couldn't find that job.",ui:homeUi});await s.from("conversation_sessions").update({state:"router_edit_location",context:{editing_job_id:id}}).eq("channel",input.channel??"whatsapp").eq("external_user_id",phone);return json({ok:true,reply:"Send the new location as: Suburb, City, Province."})}
if(c&&message.startsWith("EDITSVC:")){const id=message.slice(8);return json({ok:true,reply:"Choose the correct service.",ui:await editSkillUi(s,id,0)})}
if(c&&message.startsWith("ESVCPAGE:")){const[,id,p]=message.split(":");return json({ok:true,reply:"Choose the correct service.",ui:await editSkillUi(s,id,Number(p)||0)})}
if(c&&message.startsWith("ESKILL:")){const parts=message.split(":");const id=parts[1],code=parts.slice(2).join(":");const j=await jobOwned(s,c.id,id);if(!j)return json({ok:true,reply:"I couldn't find that job.",ui:homeUi});const sk=await s.from("skills").select("id").eq("code",code).maybeSingle();if(!sk.data)return json({ok:true,reply:"That service is not available.",ui:await editSkillUi(s,id,0)});await s.from("jobs").update({skill_id:sk.data.id,status:"matching"}).eq("id",id);await s.from("job_matches").update({status:"expired"}).eq("job_id",id).eq("status","offered");const fresh=await jobOwned(s,c.id,id);const outbound=await rematch(s,fresh);return json({ok:true,reply:await jobCard(s,fresh),ui:jobMenu(id,fresh.status),outbound})}
if(c&&message.startsWith("CANCEL:")){const id=message.slice(7);const j=await jobOwned(s,c.id,id);if(!j)return json({ok:true,reply:"I couldn't find that job.",ui:homeUi});await s.from("jobs").update({status:"cancelled"}).eq("id",id).in("status",["open","matching"]);await s.from("job_matches").update({status:"expired"}).eq("job_id",id).eq("status","offered");return json({ok:true,reply:"Job cancelled. No more handymen will be matched to it.",ui:{type:"list",body:"What next?",button:"Choose",rows:[{id:"NEW_REQUEST",title:"New request"},{id:"CUSTOMER_JOBS",title:"My jobs"},{id:"HOME",title:"Home"}]}})}
if(message==="NEW_REQUEST"){const d=await delegate(url,key,input,"REQUEST_HELP");return json(d.body,d.status)}
if(message==="HOME")return json({ok:true,reply:"What would you like to do?",ui:homeUi});
const d=await delegate(url,key,input);if(!d.ok)return json(d.body,d.status);if(c&&d.body?.job_id){const j=await jobOwned(s,c.id,d.body.job_id);if(j)return json({...d.body,reply:await jobCard(s,j),ui:jobMenu(j.id,j.status)})}return json(d.body)}catch(e){console.error(e);return json({error:"internal_error"},500)}});
