import { createClient } from "@supabase/supabase-js";

const PASSWORD_HASH = "1ecebee07403f6e3b9ee6e73f7202767f8a86856a115a072e7e9e74729e24ab3";
const enc = new TextEncoder();

function serviceKey(){
  const raw=Deno.env.get("SUPABASE_SECRET_KEYS");
  if(raw){try{const p=JSON.parse(raw);if(typeof p.default==="string"&&p.default)return p.default}catch{}}
  return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
}
function esc(s:unknown){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]??c))}
function b64url(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
async function sha256(s:string){return b64url(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(s))))}
async function hexSha256(s:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(s)))].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function sign(value:string,key:string){const k=await crypto.subtle.importKey("raw",enc.encode(key),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64url(new Uint8Array(await crypto.subtle.sign("HMAC",k,enc.encode(value))))}
async function makeSession(key:string){const exp=Math.floor(Date.now()/1000)+8*60*60;const body=String(exp);return `${body}.${await sign(body,key)}`}
async function validSession(req:Request,key:string){const cookie=req.headers.get("cookie")??"";const token=cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("hc_admin="))?.slice(9);if(!token)return false;const [exp,sig]=token.split(".");if(!exp||!sig||Number(exp)<Math.floor(Date.now()/1000))return false;return sig===await sign(exp,key)}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const html=(body:string,status=200,extra:HeadersInit={})=>new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","content-security-policy":"default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",...extra}});

const LOGIN=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>HandyConnect Admin</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui;background:#f4f7f6;color:#10221b;min-height:100vh;display:grid;place-items:center}.card{width:min(430px,92vw);background:#fff;border:1px solid #dfe9e5;border-radius:20px;padding:32px;box-shadow:0 18px 60px #173d2d18}.brand{font-weight:800;font-size:25px;color:#126b49}.sub{color:#61756d;margin:8px 0 26px}.label{display:block;font-size:13px;font-weight:700;margin-bottom:7px}input{width:100%;padding:14px 15px;border:1px solid #cbd9d3;border-radius:12px;font-size:16px;outline:none}input:focus{border-color:#16855b;box-shadow:0 0 0 3px #16855b18}button{width:100%;margin-top:14px;border:0;background:#126b49;color:#fff;padding:14px;border-radius:12px;font-weight:800;font-size:15px;cursor:pointer}.note{font-size:12px;color:#71827b;margin-top:18px;text-align:center}</style></head><body><form class="card" method="post"><div class="brand">HandyConnect</div><div class="sub">Operations dashboard</div><label class="label" for="password">Admin password</label><input id="password" name="password" type="password" autocomplete="current-password" required autofocus><button type="submit">Sign in</button><div class="note">Private administration area</div></form></body></html>`;

const DASH=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>HandyConnect Operations</title><style>
:root{--ink:#10221b;--muted:#657970;--green:#126b49;--bg:#f3f6f5;--line:#dfe8e4;--red:#a83232;--amber:#9a6700}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.45 Inter,ui-sans-serif,system-ui}.top{height:64px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 24px;position:sticky;top:0;z-index:5}.brand{font-size:20px;font-weight:850;color:var(--green)}.top a{color:var(--muted);text-decoration:none}.wrap{max-width:1480px;margin:auto;padding:24px}.headline{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:18px}.headline h1{font-size:25px;margin:0}.headline p{margin:4px 0 0;color:var(--muted)}button,.btn{border:1px solid var(--line);background:#fff;border-radius:10px;padding:9px 12px;font-weight:700;cursor:pointer;color:var(--ink)}button.primary{background:var(--green);color:white;border-color:var(--green)}.stats{display:grid;grid-template-columns:repeat(6,minmax(140px,1fr));gap:12px}.stat{background:#fff;border:1px solid var(--line);border-radius:15px;padding:16px}.stat .n{font-size:28px;font-weight:850}.stat .l{color:var(--muted);font-size:12px;margin-top:3px}.tabs{display:flex;gap:7px;margin:22px 0 12px;overflow:auto}.tab.active{background:var(--ink);color:#fff;border-color:var(--ink)}.panel{display:none}.panel.active{display:block}.box{background:#fff;border:1px solid var(--line);border-radius:15px;overflow:hidden}.boxhead{display:flex;justify-content:space-between;align-items:center;padding:15px 17px;border-bottom:1px solid var(--line)}.boxhead h2{font-size:15px;margin:0}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;min-width:760px}th,td{text-align:left;padding:12px 15px;border-bottom:1px solid #edf2f0;vertical-align:top}th{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);background:#fbfcfc}tr:last-child td{border-bottom:0}.pill{display:inline-block;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:750;background:#edf4f1}.pill.matching,.pill.pending,.pill.open{background:#fff3d6;color:#7c5200}.pill.completed,.pill.verified,.pill.succeeded,.pill.sent{background:#e4f5ec;color:#17623f}.pill.failed,.pill.rejected,.pill.suspended{background:#fde8e8;color:#8f2f2f}.muted{color:var(--muted)}.empty{padding:30px;text-align:center;color:var(--muted)}.actions{display:flex;gap:6px;flex-wrap:wrap}.actions button{padding:6px 9px;font-size:12px}.danger{color:var(--red)}.good{color:var(--green)}.error{background:#fde8e8;color:#852f2f;padding:12px;border-radius:12px;margin-bottom:15px;display:none}@media(max-width:950px){.stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:580px){.wrap{padding:14px}.top{padding:0 14px}.stats{grid-template-columns:repeat(2,1fr)}.headline{align-items:start;flex-direction:column}}
</style></head><body><header class="top"><div class="brand">HandyConnect · Ops</div><a href="?logout=1">Sign out</a></header><main class="wrap"><div class="headline"><div><h1>Marketplace operations</h1><p id="updated">Loading live data…</p></div><button class="primary" onclick="load()">Refresh</button></div><div id="error" class="error"></div><section class="stats" id="stats"></section><nav class="tabs" id="tabs"><button class="tab active" data-p="jobs">Jobs</button><button class="tab" data-p="handymen">Handymen</button><button class="tab" data-p="reports">Reports</button><button class="tab" data-p="payments">Payments</button><button class="tab" data-p="notifications">Notifications</button></nav><section id="jobs" class="panel active"></section><section id="handymen" class="panel"></section><section id="reports" class="panel"></section><section id="payments" class="panel"></section><section id="notifications" class="panel"></section></main><script>
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const P=s=>'<span class="pill '+E(s)+'">'+E(String(s||'unknown').replaceAll('_',' '))+'</span>';const D=s=>s?new Date(s).toLocaleString():'—';
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.p).classList.add('active')});
async function api(body){const r=await fetch(location.pathname+'?api=1',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.status===401){location.reload();return}const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x}
function box(title,headers,rows){return '<div class="box"><div class="boxhead"><h2>'+E(title)+'</h2><span class="muted">'+rows.length+' shown</span></div>'+(rows.length?'<div class="scroll"><table><thead><tr>'+headers.map(h=>'<th>'+E(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>':'<div class="empty">Nothing to show.</div>')+'</div>'}
async function act(action,data,msg){if(msg&&!confirm(msg))return;await api({action,...data});await load()}
function render(x){const s=x.stats;document.getElementById('stats').innerHTML=[['Jobs',s.jobs],['Searching',s.searching],['Active',s.active_jobs],['Handymen',s.handymen],['Available',s.available],['Open reports',s.open_reports]].map(a=>'<div class="stat"><div class="n">'+E(a[1])+'</div><div class="l">'+E(a[0])+'</div></div>').join('');
 document.getElementById('jobs').innerHTML=box('Recent jobs',['Job','Customer','Area','Status','Created'],x.jobs.map(j=>'<tr><td><strong>'+E(j.description)+'</strong><div class="muted">'+E(j.skill||'General')+'</div></td><td>'+E(j.customer_name||'—')+'<div class="muted">'+E(j.customer_phone||'')+'</div></td><td>'+E([j.suburb,j.city].filter(Boolean).join(', '))+'</td><td>'+P(j.status)+'</td><td>'+E(D(j.created_at))+'</td></tr>'));
 document.getElementById('handymen').innerHTML=box('Handymen',['Provider','Availability','Verification','Rating','Jobs','Actions'],x.handymen.map(h=>'<tr><td><strong>'+E(h.full_name)+'</strong><div class="muted">'+E(h.phone)+'</div></td><td>'+P(h.availability_status)+'</td><td>'+P(h.verification_status)+'</td><td>'+E(h.average_rating)+'/5</td><td>'+E(h.completed_jobs)+'</td><td><div class="actions">'+(h.verification_status!=='verified'?'<button class="good" onclick="act(\'verify\',{id:\''+h.id+'\'})">Verify</button>':'')+(h.status==='active'?'<button class="danger" onclick="act(\'suspend\',{id:\''+h.id+'\'},\'Suspend this handyman?\')">Suspend</button>':'<button onclick="act(\'activate\',{id:\''+h.id+'\'})">Activate</button>')+'</div></td></tr>'));
 document.getElementById('reports').innerHTML=box('Open reports',['Job','Reporter','Reason','Details','Created','Actions'],x.reports.map(r=>'<tr><td>'+E(r.job_description||'—')+'</td><td>'+E(r.reporter_phone)+'</td><td>'+P(r.reason)+'</td><td>'+E(r.details||'—')+'</td><td>'+E(D(r.created_at))+'</td><td><div class="actions"><button class="good" onclick="act(\'resolve_report\',{id:\''+r.id+'\'})">Resolve</button><button onclick="act(\'dismiss_report\',{id:\''+r.id+'\'})">Dismiss</button></div></td></tr>'));
 document.getElementById('payments').innerHTML=box('Recent payments',['Handyman','Purpose','Amount','Provider','Status','Created'],x.payments.map(p=>'<tr><td>'+E(p.handyman_name||'—')+'<div class="muted">'+E(p.handyman_phone||'')+'</div></td><td>'+E(p.purpose)+'</td><td>R '+E((p.amount_cents/100).toFixed(2))+'</td><td>'+E(p.provider)+'</td><td>'+P(p.status)+'</td><td>'+E(D(p.created_at))+'</td></tr>'));
 document.getElementById('notifications').innerHTML=box('Notification outbox',['Recipient','Kind','Status','Attempts','Last error','Created'],x.notifications.map(n=>'<tr><td>'+E(n.recipient_phone)+'</td><td>'+E(n.kind)+'</td><td>'+P(n.status)+'</td><td>'+E(n.attempts)+'</td><td>'+E(n.last_error||'—')+'</td><td>'+E(D(n.created_at))+'</td></tr>'));
 document.getElementById('updated').textContent='Live data · updated '+new Date().toLocaleTimeString();}
async function load(){document.getElementById('error').style.display='none';try{render(await api({action:'summary'}))}catch(e){const z=document.getElementById('error');z.textContent=e.message;z.style.display='block'}}load();setInterval(load,60000);
</script></body></html>`;

Deno.serve(async(req)=>{
  const key=serviceKey(), url=Deno.env.get("SUPABASE_URL")??"";
  if(!key||!url)return new Response("Service unavailable",{status:503});
  const u=new URL(req.url);
  if(u.searchParams.get("logout")==="1")return html(LOGIN,200,{"set-cookie":"hc_admin=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict"});
  const authed=await validSession(req,key);
  if(!authed){
    if(req.method==="POST"){
      const ct=req.headers.get("content-type")??"";
      if(ct.includes("application/x-www-form-urlencoded")){const f=await req.formData();const pw=String(f.get("password")??"");if(await hexSha256(pw)===PASSWORD_HASH){const token=await makeSession(key);return html(DASH,200,{"set-cookie":`hc_admin=${token}; Path=/; Max-Age=28800; HttpOnly; Secure; SameSite=Strict`})}return html(LOGIN.replace("Admin password","Incorrect password. Try again"),401)}
    }
    return html(LOGIN,401);
  }
  if(req.method==="GET")return html(DASH);
  if(req.method!=="POST")return json({error:"method_not_allowed"},405);
  let input:any;try{input=await req.json()}catch{return json({error:"invalid_json"},400)}
  const s=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  try{
    const action=String(input?.action??"summary");
    if(action==="summary"){
      const now=new Date().toISOString();
      const [jobsCount,searching,activeJobs,handymenCount,available,openReports,jobs,handymen,reports,payments,notifications]=await Promise.all([
        s.from("jobs").select("id",{count:"exact",head:true}),s.from("jobs").select("id",{count:"exact",head:true}).in("status",["open","matching"]),s.from("jobs").select("id",{count:"exact",head:true}).in("status",["assigned","in_progress"]),s.from("handymen").select("id",{count:"exact",head:true}),s.from("handymen").select("id",{count:"exact",head:true}).eq("availability_status","available").gt("available_until",now),s.from("user_reports").select("id",{count:"exact",head:true}).in("status",["open","reviewing"]),
        s.from("jobs").select("id,description,suburb,city,status,created_at,customers(full_name,phone),skills(name)").order("created_at",{ascending:false}).limit(50),
        s.from("handymen").select("id,full_name,phone,status,availability_status,verification_status,average_rating,completed_jobs,created_at").order("created_at",{ascending:false}).limit(100),
        s.from("user_reports").select("id,job_id,reporter_phone,reason,details,status,created_at,jobs(description)").in("status",["open","reviewing"]).order("created_at",{ascending:false}).limit(50),
        s.from("payments").select("id,purpose,amount_cents,currency,provider,status,created_at,handymen(full_name,phone)").order("created_at",{ascending:false}).limit(50),
        s.from("notification_outbox").select("id,recipient_phone,kind,status,attempts,last_error,created_at").order("created_at",{ascending:false}).limit(75)
      ]);
      for(const q of [jobsCount,searching,activeJobs,handymenCount,available,openReports,jobs,handymen,reports,payments,notifications])if(q.error)throw q.error;
      return json({ok:true,stats:{jobs:jobsCount.count??0,searching:searching.count??0,active_jobs:activeJobs.count??0,handymen:handymenCount.count??0,available:available.count??0,open_reports:openReports.count??0},jobs:(jobs.data??[]).map((j:any)=>({...j,customer_name:j.customers?.full_name,customer_phone:j.customers?.phone,skill:j.skills?.name})),handymen:handymen.data??[],reports:(reports.data??[]).map((r:any)=>({...r,job_description:r.jobs?.description})),payments:(payments.data??[]).map((p:any)=>({...p,handyman_name:p.handymen?.full_name,handyman_phone:p.handymen?.phone})),notifications:notifications.data??[]});
    }
    const id=String(input?.id??"");if(!id)return json({error:"id_required"},400);
    if(action==="verify"){const q=await s.from("handymen").update({verification_status:"verified",verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(q.error)throw q.error;return json({ok:true})}
    if(action==="suspend"||action==="activate"){const q=await s.from("handymen").update({status:action==="suspend"?"suspended":"active",availability_status:action==="suspend"?"offline":undefined,updated_at:new Date().toISOString()}).eq("id",id);if(q.error)throw q.error;return json({ok:true})}
    if(action==="resolve_report"||action==="dismiss_report"){const q=await s.rpc("resolve_user_report",{p_report_id:id,p_status:action==="resolve_report"?"resolved":"dismissed",p_resolution_notes:"Updated from operations dashboard",p_resolved_by:"dashboard"});if(q.error)throw q.error;return json({ok:true})}
    return json({error:"unknown_action"},400);
  }catch(e){console.error(e);return json({error:"dashboard_operation_failed"},500)}
});
