import { createClient } from "@supabase/supabase-js";
type Incoming={channel?:string;external_user_id?:string;external_message_id?:string;message?:string};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS")??"";if(raw){try{const p=JSON.parse(raw);if(typeof p.default==='string')return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
function parseLocation(t:string){const p=t.split(',').map(x=>x.trim()).filter(Boolean);return p.length<2?null:{suburb:p[0],city:p[1],province:p[2]??null}}
const urgencyUi={type:'buttons',body:'How soon do you need help?',buttons:[{id:'JI_URGENT',title:'As soon as possible'},{id:'JI_TODAY',title:'Today'},{id:'JI_FLEXIBLE',title:'Flexible'}]};
function addressUi(rows:any[]){return{type:'list',body:'Where should the handyman come?',button:'Choose address',rows:[...rows.map((a:any)=>({id:`JI_ADDR:${a.id}`,title:String(a.label||'Saved address').slice(0,24),description:`${a.street_address}, ${a.suburb}, ${a.city}`.slice(0,72)})),{id:'JI_ADDR_NEW',title:'Use another address',description:'Enter a new service address'}]}}
async function call(url:string,k:string,name:string,input:Incoming){const r=await fetch(`${url}/functions/v1/${name}`,{method:'POST',headers:{apikey:k,'content-type':'application/json'},body:JSON.stringify(input)});if(!r.ok)return{handled:false};return await r.json()}
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'method_not_allowed'},405);const k=key(),url=Deno.env.get('SUPABASE_URL')??'';if(!k||!url||req.headers.get('apikey')!==k)return json({error:'unauthorized'},401);let input:Incoming;try{input=await req.json()}catch{return json({error:'invalid_json'},400)}const phone=input.external_user_id?.trim(),msg=input.message?.trim()??'';if(!phone)return json({handled:false});const s=createClient(url,k,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
if(input.external_message_id){const claim=await s.from('whatsapp_inbound_events').insert({message_id:input.external_message_id});if(claim.error){if(claim.error.code==='23505')return json({handled:true,duplicate:true});throw claim.error}}
const q=await s.from('conversation_sessions').select('id,state,context').eq('channel',input.channel??'whatsapp').eq('external_user_id',phone).maybeSingle();if(q.error)throw q.error;const x=q.data;const cust=await s.from('customers').select('id,full_name,preferred_name').eq('phone',phone).maybeSingle();
if(x?.state==='ji_location'){const loc=parseLocation(msg);if(!loc)return json({handled:true,reply:'Please send at least Suburb, City. Example: Langa, Cape Town'});const c={...(x.context??{}),...loc};if(cust.data?.id){const a=await s.from('customer_addresses').select('id,label,street_address,suburb,city,province').eq('customer_id',cust.data.id).order('is_default',{ascending:false}).order('last_used_at',{ascending:false}).limit(5);if((a.data??[]).length){await s.from('conversation_sessions').update({state:'ji_saved_address',context:c}).eq('id',x.id);return json({handled:true,reply:'Choose a saved address or use another one.',ui:addressUi(a.data??[])})}}await s.from('conversation_sessions').update({state:'ji_address',context:c}).eq('id',x.id);return json({handled:true,reply:'What is the street address?\nIt stays private until a handyman accepts.'})}
if(x?.state==='ji_saved_address'){if(msg==='JI_ADDR_NEW'){await s.from('conversation_sessions').update({state:'ji_address'}).eq('id',x.id);return json({handled:true,reply:'What is the street address?\nIt stays private until a handyman accepts.'})}if(msg.startsWith('JI_ADDR:')&&cust.data?.id){const id=msg.slice(8),a=await s.from('customer_addresses').select('id,street_address,suburb,city,province').eq('id',id).eq('customer_id',cust.data.id).maybeSingle();if(!a.data)return json({handled:true,reply:'That saved address is no longer available.',ui:{type:'buttons',body:'Address',buttons:[{id:'JI_ADDR_NEW',title:'New address'}]}});await s.from('customer_addresses').update({last_used_at:new Date().toISOString()}).eq('id',a.data.id);await s.from('conversation_sessions').update({state:'ji_urgency',context:{...(x.context??{}),street_address:a.data.street_address,suburb:a.data.suburb,city:a.data.city,province:a.data.province}}).eq('id',x.id);return json({handled:true,reply:'Address selected.',ui:urgencyUi})}return json({handled:true,reply:'Choose a saved address or use another address.'})}
if(x?.state==='ji_address'){if(msg.length<5)return json({handled:true,reply:'Please send the street number and street name.'});await s.from('conversation_sessions').update({state:'ji_urgency',context:{...(x.context??{}),street_address:msg}}).eq('id',x.id);return json({handled:true,reply:'Address saved privately.',ui:urgencyUi})}
const hj=await call(url,k,'handyman-job-history-router',input);if(hj?.handled)return json(hj);const dup=await call(url,k,'duplicate-job-router',input);if(dup?.handled)return json(dup);return json(await call(url,k,'customer-home-router',input))});