import { createClient } from "@supabase/supabase-js";
type Incoming={channel?:string;external_user_id?:string;message?:string};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS")??"";if(raw){try{const p=JSON.parse(raw);if(typeof p.default==='string')return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
function homeText(name?:string){return name?`Hi ${name} 👋\nWhat do you need?`:'What do you need?'}
function home(name?:string){return{type:'buttons',body:homeText(name),buttons:[{id:'REQUEST_HELP',title:'Request handyman'},{id:'MY_JOBS',title:'My jobs'},{id:'CUST_MORE',title:'More'}]}}
function more(){return{type:'list',body:'More options',button:'Choose',rows:[{id:'CUST_ADDRESSES',title:'Saved addresses'},{id:'CUST_PROFILE',title:'My profile'},{id:'CUST_HELP',title:'Help'},{id:'HOME',title:'Home'}]}}
async function call(url:string,k:string,target:string,i:Incoming){const r=await fetch(`${url}/functions/v1/${target}`,{method:'POST',headers:{apikey:k,'content-type':'application/json'},body:JSON.stringify(i)});return{status:r.status,body:await r.json().catch(()=>({handled:false}))}}
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'method_not_allowed'},405);const k=key(),url=Deno.env.get('SUPABASE_URL')??'';if(!k||!url||req.headers.get('apikey')!==k)return json({error:'unauthorized'},401);let i:Incoming;try{i=await req.json()}catch{return json({error:'invalid_json'},400)}const phone=i.external_user_id?.trim(),msg=i.message?.trim()??'';if(!phone)return json({handled:false});const s=createClient(url,k,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const h=await s.from('handymen').select('id').eq('phone',phone).maybeSingle();if(h.data)return json({handled:false});let c:any=await s.from('customers').select('id,full_name,preferred_name,email,onboarding_completed_at').eq('phone',phone).maybeSingle();const session=await s.from('conversation_sessions').select('id,state,context').eq('channel',i.channel??'whatsapp').eq('external_user_id',phone).maybeSingle();
if(session.data?.state==='customer_name'){const name=msg.replace(/\s+/g,' ').trim();if(name.length<2||name.length>80)return json({handled:true,reply:'What name should I call you?'});await s.from('customers').update({full_name:name,preferred_name:name.split(' ')[0],onboarding_completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',c.data.id);await s.from('conversation_sessions').update({state:'ready',flow:'ready',context:{}}).eq('id',session.data.id);const first=name.split(' ')[0];return json({handled:true,reply:homeText(first),ui:home(first)})}
const greet=['hi','hello','hey','menu','start','home'].includes(msg.toLowerCase())||msg==='HOME';if(greet){if(!c.data){const n=await s.from('customers').insert({phone}).select('id').single();c={data:{id:n.data.id}}}if(!c.data.full_name){if(session.data?.id)await s.from('conversation_sessions').update({flow:'customer_onboarding',state:'customer_name',context:{}}).eq('id',session.data.id);else await s.from('conversation_sessions').insert({channel:i.channel??'whatsapp',external_user_id:phone,flow:'customer_onboarding',state:'customer_name',context:{}});return json({handled:true,reply:'Welcome to HandyConnect 👋\nWhat name should I call you?'})}const first=c.data.preferred_name||String(c.data.full_name).split(' ')[0];return json({handled:true,reply:homeText(first),ui:home(first)})}
if(msg==='MY_JOBS'||msg==='CUSTOMER_JOBS'||msg.startsWith('CJOB:')||msg.startsWith('CSTALE:')){const r=await call(url,k,'customer-job-history-router',i);return json(r.body,r.status)}
const editCommand=msg.startsWith('EDIT_JOB:')||msg.startsWith('EDITLOC:')||msg.startsWith('EDITSVC:')||msg.startsWith('ESVCPAGE:')||msg.startsWith('ESKILL:')||session.data?.state==='router_edit_location';if(editCommand){const editingId=String(session.data?.context?.editing_job_id??'');const r=await call(url,k,'customer-job-router',i);if(msg.startsWith('EDIT_JOB:'))return json({handled:true,reply:'What would you like to change?',ui:r.body?.ui},r.status);if(msg.startsWith('EDITLOC:'))return json({handled:true,reply:'Where is the job?\nSend suburb, city and province.\nExample: Langa, Cape Town, Western Cape'},r.status);if(session.data?.state==='router_edit_location'&&r.status<300)return json({handled:true,reply:'Location updated. I’ll continue looking for a handyman.',ui:{type:'buttons',body:'Request updated',buttons:[{id:editingId?`CJOB:${editingId}`:'MY_JOBS',title:'View request'},{id:'MY_JOBS',title:'My jobs'},{id:'HOME',title:'Home'}]},outbound:r.body?.outbound},r.status);if(msg.startsWith('ESKILL:')&&r.status<300)return json({handled:true,reply:'Service updated. I’ll continue looking for a handyman.',ui:{type:'buttons',body:'Request updated',buttons:[{id:'MY_JOBS',title:'My jobs'},{id:'HOME',title:'Home'}]},outbound:r.body?.outbound},r.status);return json({...r.body,handled:true},r.status)}
if(msg==='CUST_MORE')return json({handled:true,reply:'More options',ui:more()});if(msg==='CUST_PROFILE'&&c.data)return json({handled:true,reply:`Name: ${c.data.full_name||'Not set'}\nPhone: ${phone}\nEmail: ${c.data.email||'Not set'}`,ui:{type:'buttons',body:'Profile',buttons:[{id:'HOME',title:'Home'}]}});if(msg==='CUST_ADDRESSES'&&c.data){const a=await s.from('customer_addresses').select('label,street_address,suburb,city,is_default').eq('customer_id',c.data.id).order('is_default',{ascending:false}).order('last_used_at',{ascending:false}).limit(10);return json({handled:true,reply:(a.data??[]).length?`Saved addresses\n${(a.data??[]).map((x:any)=>`• ${x.label}${x.is_default?' · default':''}: ${x.street_address}, ${x.suburb}, ${x.city}`).join('\n')}`:'No saved addresses yet.',ui:{type:'buttons',body:'Saved addresses',buttons:[{id:'REQUEST_HELP',title:'Request handyman'},{id:'HOME',title:'Home'}]}})}if(msg==='CUST_HELP')return json({handled:true,reply:'Request help, choose your location and timing, then HandyConnect looks for a suitable provider. You agree the quote before work starts, and your street address is only shared after a handyman accepts.',ui:{type:'buttons',body:'Need help?',buttons:[{id:'REQUEST_HELP',title:'Request handyman'},{id:'HOME',title:'Home'}]}});return json({handled:false})});