insert into storage.buckets(id,name,public,file_size_limit) values('job-evidence','job-evidence',false,10485760) on conflict(id) do update set public=false,file_size_limit=10485760;
alter table public.job_evidence add column if not exists storage_path text, add column if not exists sha256 text, add column if not exists byte_size bigint;
create unique index if not exists uq_job_evidence_storage_path on public.job_evidence(storage_path) where storage_path is not null;
create or replace function public.record_job_evidence_v2(p_job_id uuid,p_report_id uuid,p_uploader_phone text,p_evidence_type text,p_media_id text,p_media_type text,p_mime_type text,p_file_name text,p_storage_path text,p_sha256 text,p_byte_size bigint)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_customer uuid;v_handyman uuid;v_role text;v_id uuid;begin
select c.id into v_customer from jobs j join customers c on c.id=j.customer_id where j.id=p_job_id and c.phone=p_uploader_phone;
if v_customer is not null then v_role:='customer';else select h.id into v_handyman from job_assignments a join handymen h on h.id=a.handyman_id where a.job_id=p_job_id and h.phone=p_uploader_phone order by a.assigned_at desc limit 1;if v_handyman is null then raise exception 'uploader_not_party_to_job';end if;v_role:='handyman';end if;
if p_report_id is not null and not exists(select 1 from user_reports where id=p_report_id and job_id=p_job_id) then raise exception 'report_not_for_job';end if;
insert into job_evidence(job_id,report_id,uploader_phone,uploader_role,evidence_type,media_id,media_type,mime_type,file_name,storage_path,sha256,byte_size) values(p_job_id,p_report_id,p_uploader_phone,v_role,p_evidence_type,p_media_id,p_media_type,p_mime_type,p_file_name,p_storage_path,p_sha256,p_byte_size) returning id into v_id;
insert into job_events(job_id,event_type,actor_type,metadata) values(p_job_id,'evidence_submitted',v_role,jsonb_build_object('evidence_id',v_id,'evidence_type',p_evidence_type,'report_id',p_report_id,'sha256',p_sha256,'byte_size',p_byte_size));return v_id;end $$;
revoke all on function public.record_job_evidence_v2(uuid,uuid,text,text,text,text,text,text,text,text,bigint) from public,anon,authenticated;grant execute on function public.record_job_evidence_v2(uuid,uuid,text,text,text,text,text,text,text,text,bigint) to service_role;
create or replace view public.job_evidence_ops as select e.id,e.job_id,e.report_id,e.uploader_phone,e.uploader_role,e.evidence_type,e.media_type,e.mime_type,e.file_name,e.caption,e.storage_path,e.sha256,e.byte_size,e.created_at,j.description job_description,j.status job_status,r.reason report_reason,r.status report_status from job_evidence e join jobs j on j.id=e.job_id left join user_reports r on r.id=e.report_id;