import { createClient } from "@supabase/supabase-js";
type Incoming={channel?:"whatsapp"|"test"|"admin";external_user_id?:string;external_message_id?:string;message?:string;media?:{id:string;type:string;mime_type?:string;filename?:string}};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const p=JSON.parse(raw);if(typeof p.default==="string"&&p.default)return p.default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const types=[['before_photo','Before photo'],['after_photo','After photo'],['receipt','Receipt'],['quote_support','Quote support'],['dispute','Dispute evidence'],['other','Other evidence']];
async function canAccess(s:any,phone:string,jobId:string){const c=await s.from('customers').select('id').eq('phone',phone).maybeSingle();if(c.data){const j=await s.from('jobs').select('id').eq('id',jobId).eq('customer_id',c.data.id).maybeSingle();if(j.data)return true}const h=await s.from('handymen').select('id').eq('phone',phone).maybeSingle();if(h.data){const a=await s.from('job_assignments').select('id').eq('job_id',jobId).eq('handyman_id',h.data.id).limit(1).maybeSingle();if(a.data)return true}return false}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const k=key(),url=Deno.env.get("SUPABASE_URL")??"";if(!k||!url||req.headers.get("apikey")!==k)return json({error:"unauthorized"},401);let input:Incoming;try{input=await req.json()}catch{return json({error:"invalid_json"},400)}const phone=input.external_user_id?.trim(),message=input.message?.trim();if(!phone||!message)return json({handled:false});const s=createClient(url,k,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});try{const session=await s.from('conversation_sessions').select('id,state,context').eq('channel',input.channel??'whatsapp').eq('external_user_id',phone).maybeSingle();
 if(input.media&&session.data?.state==='evidence_router_upload'){const ctx=session.data.context??{},jobId=String(ctx.job_id??''),reportId=ctx.report_id?String(ctx.report_id):null,evidenceType=String(ctx.evidence_type??'other');if(!jobId||!(await canAccess(s,phone,jobId)))return json({handled:true,ok:true,reply:'That evidence request expired. Open the job or report and choose Add evidence again.'});const r=await s.rpc('record_job_evidence',{p_job_id:jobId,p_report_id:reportId,p_uploader_phone:phone,p_evidence_type:evidenceType,p_media_id:input.media.id,p_media_type:input.media.type,p_mime_type:input.media.mime_type??null,p_file_name:input.media.filename??null,p_caption:null});if(r.error)throw r.error;await s.from('conversation_sessions').update({state:'ready',context:{}}).eq('id',session.data.id);return json({handled:true,ok:true,reply:'Evidence saved to this job. It is now part of the immutable job record.',ui:{type:'buttons',body:'Evidence saved',buttons:[{id:`EVIDENCE_ADD:${jobId}${reportId?':'+reportId:''}`,title:'Add another'},{id:'HOME',title:'Home'}]}})}
 if(message.startsWith('EVIDENCE_ADD:')){const p=message.split(':'),jobId=p[1],reportId=p[2]||null;if(!jobId||!(await canAccess(s,phone,jobId)))return json({handled:true,ok:true,reply:'That job is not linked to your account.'});return json({handled:true,ok:true,reply:'What kind of evidence are you adding?',ui:{type:'list',body:'Choose evidence type',button:'Choose type',rows:types.map(t=>({id:`EVIDENCE_TYPE:${t[0]}:${jobId}${reportId?':'+reportId:''}`,title:t[1]}))}})}
 if(message.startsWith('EVIDENCE_TYPE:')){const p=message.split(':'),evidenceType=p[1],jobId=p[2],reportId=p[3]||null;if(!types.some(t=>t[0]===evidenceType)||!jobId||!(await canAccess(s,phone,jobId)))return json({handled:true,ok:true,reply:'That evidence option is no longer available.'});if(session.data?.id)await s.from('conversation_sessions').update({state:'evidence_router_upload',context:{job_id:jobId,report_id:reportId,evidence_type:evidenceType}}).eq('id',session.data.id);return json({handled:true,ok:true,reply:'Attach one clear photo or document now. Do not include passwords, PINs or unrelated private information.'})}
 return json({handled:false});
}catch(e){console.error(e);return json({handled:true,error:'evidence_failed'},500)}});